/**
 * hotQuizzesData.js
 * Phase E: "Hot Quizzes" and "Fun Quizzes" format definitions and seed data.
 * Formats: "image" | "flag" | "logo" | "map" | "riddle" | "fact"
 */

export const FORMAT_CONFIG = {
  image: {
    label: "Image",
    labelHi: "फोटो",
    badge: "Image",
    emoji: "🖼️",
    tint: "#EEF2FF",
    border: "#C7D2FE",
    textCol: "#4338CA",
  },
  flag: {
    label: "Flag",
    labelHi: "झंडा",
    badge: "Flag",
    emoji: "🚩",
    tint: "#FEF3C7",
    border: "#FDE68A",
    textCol: "#B45309",
  },
  logo: {
    label: "Logo",
    labelHi: "लोगो",
    badge: "Logo",
    emoji: "🏷️",
    tint: "#FCE7F3",
    border: "#FBCFE8",
    textCol: "#BE185D",
  },
  map: {
    label: "Map",
    labelHi: "मानचित्र",
    badge: "Map",
    emoji: "🗺️",
    tint: "#DCFCE7",
    border: "#BBF7D0",
    textCol: "#15803D",
  },
  riddle: {
    label: "Riddle",
    labelHi: "पहेली",
    badge: "Riddle",
    emoji: "🧩",
    tint: "#F3E8FF",
    border: "#E9D5FF",
    textCol: "#7E22CE",
  },
  fact: {
    label: "Fact",
    labelHi: "तथ्य",
    badge: "Fact",
    emoji: "💡",
    tint: "#E0F2FE",
    border: "#BAE6FD",
    textCol: "#0369A1",
  },
};

export const HOT_QUIZZES_SEED = [
  {
    id: "guess-the-personality",
    slug: "guess-the-personality",
    title: "Guess the Personality",
    titleHi: "महान हस्तियों को पहचानें",
    format: "image",
    hot: true,
    hotRank: 1,
    emoji: "👤",
    tint: "#EEF2FF",
    border: "#C7D2FE",
    questionCount: 20,
    plays: 14250,
    coverImage: "https://images.unsplash.com/photo-1544717305-2782549b5136?w=600&auto=format&fit=crop&q=80",
    description: "Identify world-famous leaders, scientists, artists and visionaries.",
    descriptionHi: "विश्व प्रसिद्ध नेताओं, वैज्ञानिकों, कलाकारों और विचारकों को पहचानें।",
    questions: [
      {
        id: "gtp-1",
        difficulty: "easy",
        text: "Who is known as the 'Father of the Indian Nation'?",
        textHi: "किन्हें 'राष्ट्रपिता' के रूप में जाना जाता है?",
        media: {
          type: "image",
          url: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Portrait_Gandhi.jpg/480px-Portrait_Gandhi.jpg",
          alt: "Portrait of Mahatma Gandhi with round spectacles",
          credit: "Public Domain / Wikimedia",
        },
        optionLayout: "text",
        options: ["Mahatma Gandhi", "Jawaharlal Nehru", "Subhas Chandra Bose", "Sardar Patel"],
        optionsHi: ["महात्मा गांधी", "जवाहरलाल नेहरू", "सुभाष चंद्र बोस", "सरदार पटेल"],
        correctIndex: 0,
        explanation: "Mahatma Gandhi led India's non-violent independence movement.",
        explanationHi: "महात्मा गांधी ने भारत के अहिंसक स्वतंत्रता संग्राम का नेतृत्व किया।",
      },
      {
        id: "gtp-2",
        difficulty: "easy",
        text: "Identify the famous scientist known as the 'Missile Man of India'.",
        textHi: "'भारत के मिसाइल मैन' के रूप में प्रसिद्ध वैज्ञानिक को पहचानें।",
        media: {
          type: "image",
          url: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/A._P._J._Abdul_Kalam_in_2008.jpg/480px-A._P._J._Abdul_Kalam_in_2008.jpg",
          alt: "Dr. A.P.J. Abdul Kalam",
          credit: "Wikimedia Commons",
        },
        optionLayout: "text",
        options: ["Dr. A.P.J. Abdul Kalam", "Dr. Homi Bhabha", "Dr. Vikram Sarabhai", "Sir C.V. Raman"],
        optionsHi: ["डॉ. ए.पी.जे. अब्दुल कलाम", "डॉ. होमी भाभा", "डॉ. विक्रम साराभाई", "सर सी.वी. रमन"],
        correctIndex: 0,
        explanation: "Dr. Kalam played a pivotal role in India's civilian space and military missile programs.",
        explanationHi: "डॉ. कलाम ने भारत के अंतरिक्ष और सैन्य मिसाइल कार्यक्रमों में महत्वपूर्ण भूमिका निभाई।",
      },
      {
        id: "gtp-3",
        difficulty: "medium",
        text: "Which iconic physicist formulated the General Theory of Relativity?",
        textHi: "सापेक्षता के सामान्य सिद्धांत को प्रतिपादित करने वाले प्रतिष्ठित भौतिक विज्ञानी कौन हैं?",
        media: {
          type: "image",
          url: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Einstein_1921_by_F_Schmutzer_-_restoration.jpg/480px-Einstein_1921_by_F_Schmutzer_-_restoration.jpg",
          alt: "Albert Einstein portrait",
          credit: "F Schmutzer / Wikimedia Commons",
        },
        optionLayout: "text",
        options: ["Albert Einstein", "Isaac Newton", "Niels Bohr", "Max Planck"],
        optionsHi: ["अल्बर्ट आइंस्टीन", "आइजैक न्यूटन", "नील्स बोर", "मैक्स प्लैंक"],
        correctIndex: 0,
        explanation: "Albert Einstein published the General Theory of Relativity in 1915.",
        explanationHi: "अल्बर्ट आइंस्टीन ने 1915 में सापेक्षता का सामान्य सिद्धांत प्रकाशित किया था।",
      },
    ],
  },
  {
    id: "flags-of-the-world",
    slug: "flags-of-the-world",
    title: "Flags of the World",
    titleHi: "दुनिया के राष्ट्रीय ध्वज",
    format: "flag",
    hot: true,
    hotRank: 2,
    emoji: "🚩",
    tint: "#FEF3C7",
    border: "#FDE68A",
    questionCount: 20,
    plays: 18900,
    coverImage: "https://images.unsplash.com/photo-1526478806334-5fd488fcaabc?w=600&auto=format&fit=crop&q=80",
    description: "Identify nations by their national flags, emblems and tricolors.",
    descriptionHi: "राष्ट्रीय ध्वजों और प्रतीकों से विभिन्न देशों को पहचानें।",
    questions: [
      {
        id: "fotw-1",
        difficulty: "easy",
        text: "Which country does this flag belong to featuring the Ashoka Chakra?",
        textHi: "अशोक चक्र से सुशोभित यह राष्ट्रीय ध्वज किस देश का है?",
        media: {
          type: "image",
          url: "https://upload.wikimedia.org/wikipedia/en/thumb/4/41/Flag_of_India.svg/480px-Flag_of_India.svg.png",
          alt: "Tricolor flag of India with navy blue Ashoka Chakra",
          credit: "Government of India / Wikimedia",
        },
        optionLayout: "text",
        options: ["India", "Ireland", "Niger", "Ivory Coast"],
        optionsHi: ["भारत", "आयरलैंड", "नाइजर", "आइवरी कोस्ट"],
        correctIndex: 0,
        explanation: "The National Flag of India features saffron, white, and green with the 24-spoke Ashoka Chakra.",
        explanationHi: "भारत का राष्ट्रीय ध्वज केसरिया, सफेद और हरे रंग का है जिसमें 24 तीलियों वाला अशोक चक्र है।",
      },
      {
        id: "fotw-2",
        difficulty: "easy",
        text: "Identify the country with a maple leaf on its national flag.",
        textHi: "अपने राष्ट्रीय ध्वज पर मेपल की पत्ती वाले देश की पहचान करें।",
        media: {
          type: "image",
          url: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Flag_of_Canada_%28Pantone%29.svg/480px-Flag_of_Canada_%28Pantone%29.svg.png",
          alt: "Flag of Canada featuring red maple leaf",
          credit: "Wikimedia Commons",
        },
        optionLayout: "text",
        options: ["Canada", "Australia", "New Zealand", "United Kingdom"],
        optionsHi: ["कनाडा", "ऑस्ट्रेलिया", "न्यूजीलैंड", "यूनाइटेड किंगडम"],
        correctIndex: 0,
        explanation: "The red stylized 11-pointed maple leaf is the national symbol of Canada.",
        explanationHi: "लाल रंग की 11 नुकीली मेपल पत्ती कनाडा का राष्ट्रीय प्रतीक है।",
      },
      {
        id: "fotw-3",
        difficulty: "medium",
        text: "Which country is represented by the red circle on a white field?",
        textHi: "सफेद पृष्ठभूमि पर लाल वृत्त किस देश का प्रतिनिधित्व करता है?",
        media: {
          type: "image",
          url: "https://upload.wikimedia.org/wikipedia/en/thumb/9/9e/Flag_of_Japan.svg/480px-Flag_of_Japan.svg.png",
          alt: "Flag of Japan (Nisshoki)",
          credit: "Wikimedia Commons",
        },
        optionLayout: "text",
        options: ["Japan", "South Korea", "Bangladesh", "Palau"],
        optionsHi: ["जापान", "दक्षिण कोरिया", "बांग्लादेश", "पलाउ"],
        correctIndex: 0,
        explanation: "The Hinomaru or Nisshoki represents the rising sun in Japan.",
        explanationHi: "हिनोमारु या निश्शोकी जापान में उगते सूरज का प्रतीक है।",
      },
    ],
  },
  {
    id: "brand-logo-quiz",
    slug: "brand-logo-quiz",
    title: "Brand Logo Quiz",
    titleHi: "ब्रांड लोगो क्विज़",
    format: "logo",
    hot: true,
    hotRank: 3,
    emoji: "🏷️",
    tint: "#FCE7F3",
    border: "#FBCFE8",
    questionCount: 20,
    plays: 12400,
    coverImage: "https://images.unsplash.com/photo-1542744094-3a31f272c490?w=600&auto=format&fit=crop&q=80",
    description: "Can you recognize these famous technology, automobile and luxury logos?",
    descriptionHi: "क्या आप इन मशहूर टेक्नोलॉजी और ऑटोमोबाइल ब्रांड्स के लोगो पहचान सकते हैं?",
    questions: [
      {
        id: "blq-1",
        difficulty: "easy",
        text: "Which tech giant is represented by this colorful four-quadrant window logo?",
        textHi: "कौन सी टेक कंपनी इस चार रंगों वाली विंडो लोगो से पहचानी जाती है?",
        media: {
          type: "image",
          url: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Microsoft_logo.svg/480px-Microsoft_logo.svg.png",
          alt: "Microsoft four colored squares logo",
          credit: "Microsoft Corporation",
        },
        optionLayout: "text",
        options: ["Microsoft", "Google", "Apple", "IBM"],
        optionsHi: ["माइक्रोसॉफ्ट", "गूगल", "एप्पल", "आईबीएम"],
        correctIndex: 0,
        explanation: "Microsoft's four-colored square logo represents Windows, Office, Xbox, and Bing.",
        explanationHi: "माइक्रोसॉफ्ट का चार रंगों वाला लोगो विंडोज, ऑफिस, एक्सबॉक्स और बिंग का प्रतीक है।",
      },
      {
        id: "blq-2",
        difficulty: "easy",
        text: "Which automobile brand features four interlocking rings?",
        textHi: "चार आपस में जुड़े छल्लों वाला लोगो किस कार निर्माता का है?",
        media: {
          type: "image",
          url: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Audi-Logo_2016.svg/480px-Audi-Logo_2016.svg.png",
          alt: "Audi four rings logo",
          credit: "Audi AG",
        },
        optionLayout: "text",
        options: ["Audi", "BMW", "Mercedes-Benz", "Volkswagen"],
        optionsHi: ["ऑडी", "बीएमडब्ल्यू", "मर्सिडीज-बेंज", "फॉक्सवैगन"],
        correctIndex: 0,
        explanation: "Audi's four rings represent the four companies that merged to form Auto Union in 1932.",
        explanationHi: "ऑडी के चार छल्ले 1932 में ऑटो यूनियन बनाने वाली चार कंपनियों के विलय का प्रतीक हैं।",
      },
    ],
  },
  {
    id: "indian-state-map",
    slug: "indian-state-map",
    title: "Identify the Indian State Map",
    titleHi: "भारतीय राज्य मानचित्र पहचानें",
    format: "map",
    hot: true,
    hotRank: 4,
    emoji: "🗺️",
    tint: "#DCFCE7",
    border: "#BBF7D0",
    questionCount: 20,
    plays: 16100,
    coverImage: "https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=600&auto=format&fit=crop&q=80",
    description: "Challenge your Indian geography by recognizing states from their geographic contours.",
    descriptionHi: "मानचित्र रूपरेखा से भारतीय राज्यों को पहचानकर अपने भूगोल ज्ञान को परखें।",
    questions: [
      {
        id: "ism-1",
        difficulty: "easy",
        text: "Which state is known as the 'Land of Kings' and is India's largest state by area?",
        textHi: "कौन सा राज्य 'राजाओं की भूमि' कहलाता है और क्षेत्रफल की दृष्टि से भारत का सबसे बड़ा राज्य है?",
        media: {
          type: "image",
          url: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Rajasthan_in_India_%28disputed_hatched%29.svg/480px-Rajasthan_in_India_%28disputed_hatched%29.svg.png",
          alt: "Map showing Rajasthan highlighted in northwest India",
          credit: "TUBS / Wikimedia Commons",
        },
        optionLayout: "text",
        options: ["Rajasthan", "Madhya Pradesh", "Maharashtra", "Uttar Pradesh"],
        optionsHi: ["राजस्थान", "मध्य प्रदेश", "महाराष्ट्र", "उत्तर प्रदेश"],
        correctIndex: 0,
        explanation: "Rajasthan covers 10.4% of India's total geographical area.",
        explanationHi: "राजस्थान भारत के कुल भौगोलिक क्षेत्रफल का 10.4% हिस्सा कवर करता है।",
      },
      {
        id: "ism-2",
        difficulty: "easy",
        text: "Which coastal southern state is known as 'God's Own Country'?",
        textHi: "किस दक्षिणी तटीय राज्य को 'ईश्वर का अपना घर' (God's Own Country) कहा जाता है?",
        media: {
          type: "image",
          url: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Kerala_in_India_%28disputed_hatched%29.svg/480px-Kerala_in_India_%28disputed_hatched%29.svg.png",
          alt: "Map of Kerala along the southwestern Malabar coast",
          credit: "TUBS / Wikimedia Commons",
        },
        optionLayout: "text",
        options: ["Kerala", "Tamil Nadu", "Karnataka", "Goa"],
        optionsHi: ["केरल", "तमिलनाडु", "कर्नाटक", "गोवा"],
        correctIndex: 0,
        explanation: "Kerala lies along the southwestern Malabar Coast with serene backwaters.",
        explanationHi: "केरल दक्षिण-पश्चिम मालाबार तट पर स्थित है, जो अपने शांत बैकवाटर्स के लिए प्रसिद्ध है।",
      },
    ],
  },
  {
    id: "capitals-and-monuments",
    slug: "capitals-and-monuments",
    title: "Capitals and Monuments",
    titleHi: "राजधानियां और ऐतिहासिक स्मारक",
    format: "image",
    hot: true,
    hotRank: 5,
    emoji: "🏛️",
    tint: "#EEF2FF",
    border: "#C7D2FE",
    questionCount: 20,
    plays: 9800,
    coverImage: "https://images.unsplash.com/photo-1564507592333-c60657eea523?w=600&auto=format&fit=crop&q=80",
    description: "Explore world wonders, royal palaces and iconic architectural masterpieces.",
    descriptionHi: "दुनिया के सात अजूबों, शाही महलों और ऐतिहासिक धरोहरों को पहचानें।",
    questions: [
      {
        id: "cam-1",
        difficulty: "easy",
        text: "In which city is this magnificent ivory-white marble mausoleum located?",
        textHi: "यह भव्य संगमरमरी मकबरा (ताजमहल) किस शहर में स्थित है?",
        media: {
          type: "image",
          url: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Taj_Mahal_%28Edited%29.jpeg/480px-Taj_Mahal_%28Edited%29.jpeg",
          alt: "The Taj Mahal reflected in the pool",
          credit: "Wikimedia Commons",
        },
        optionLayout: "text",
        options: ["Agra", "Delhi", "Jaipur", "Lucknow"],
        optionsHi: ["आगरा", "दिल्ली", "जयपुर", "लखनऊ"],
        correctIndex: 0,
        explanation: "The Taj Mahal was commissioned in 1631 by Mughal emperor Shah Jahan in Agra.",
        explanationHi: "ताजमहल का निर्माण 1631 में मुगल सम्राट शाहजहाँ द्वारा आगरा में कराया गया था।",
      },
      {
        id: "cam-2",
        difficulty: "easy",
        text: "Identify this famous wrought-iron lattice tower located in Paris.",
        textHi: "पेरिस में स्थित इस प्रसिद्ध एफिल टॉवर को पहचानें।",
        media: {
          type: "image",
          url: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Tour_Eiffel_Wikimedia_Commons_%28cropped%29.jpg/480px-Tour_Eiffel_Wikimedia_Commons_%28cropped%29.jpg",
          alt: "Eiffel Tower Paris",
          credit: "Wikimedia Commons",
        },
        optionLayout: "text",
        options: ["Eiffel Tower", "Leaning Tower of Pisa", "Big Ben", "Colosseum"],
        optionsHi: ["एफिल टॉवर", "पीसा की झुकी मीनार", "बिग बेन", "कोलोसियम"],
        correctIndex: 0,
        explanation: "The Eiffel Tower was constructed from 1887 to 1889 as the entrance to the 1889 World's Fair.",
        explanationHi: "एफिल टॉवर का निर्माण 1889 के विश्व मेले के प्रवेश द्वार के रूप में किया गया था।",
      },
    ],
  },
  {
    id: "guess-the-animal",
    slug: "guess-the-animal",
    title: "Guess the Animal or Bird",
    titleHi: "पशु-पक्षियों को पहचानें",
    format: "image",
    hot: true,
    hotRank: 6,
    emoji: "🦜",
    tint: "#EEF2FF",
    border: "#C7D2FE",
    questionCount: 20,
    plays: 11200,
    coverImage: "https://images.unsplash.com/photo-1546182990-dffeafbe841d?w=600&auto=format&fit=crop&q=80",
    description: "Discover wildlife treasures, rare birds and amazing creatures from across the globe.",
    descriptionHi: "दुनिया भर के वन्यजीवों, दुर्लभ पक्षियों और अनोखे जीवों की पहचान करें।",
    questions: [
      {
        id: "gta-1",
        difficulty: "easy",
        text: "Which majestic animal is the National Animal of India?",
        textHi: "कौन सा शानदार प्राणी भारत का राष्ट्रीय पशु है?",
        media: {
          type: "image",
          url: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Tiger_in_Ranthambhore.jpg/480px-Tiger_in_Ranthambhore.jpg",
          alt: "Royal Bengal Tiger in Ranthambore",
          credit: "Wikimedia Commons",
        },
        optionLayout: "text",
        options: ["Royal Bengal Tiger", "Asiatic Lion", "Indian Elephant", "Snow Leopard"],
        optionsHi: ["रॉयल बंगाल टाइगर", "एशियाई शेर", "भारतीय हाथी", "हिम तेंदुआ"],
        correctIndex: 0,
        explanation: "The Royal Bengal Tiger (Panthera tigris) was declared India's national animal in 1973.",
        explanationHi: "रॉयल बंगाल टाइगर को 1973 में भारत का राष्ट्रीय पशु घोषित किया गया था।",
      },
      {
        id: "gta-2",
        difficulty: "easy",
        text: "What is the National Bird of India, known for its vibrant plumage?",
        textHi: "अपने मनमोहक पंखों के लिए प्रसिद्ध भारत का राष्ट्रीय पक्षी कौन सा है?",
        media: {
          type: "image",
          url: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Peacock_Plumage.jpg/480px-Peacock_Plumage.jpg",
          alt: "Indian Peacock displaying colorful plumage",
          credit: "Wikimedia Commons",
        },
        optionLayout: "text",
        options: ["Indian Peacock", "Great Indian Bustard", "Flamingo", "Sarus Crane"],
        optionsHi: ["भारतीय मोर", "ग्रेट इंडियन बस्टर्ड", "फ्लेमिंगो", "सारस क्रेन"],
        correctIndex: 0,
        explanation: "The Indian Peacock was declared the National Bird of India in 1963.",
        explanationHi: "भारतीय मोर को 1963 में भारत का राष्ट्रीय पक्षी घोषित किया गया था।",
      },
    ],
  },
  {
    id: "riddles-and-brain-teasers",
    slug: "riddles-and-brain-teasers",
    title: "Riddles and Brain Teasers",
    titleHi: "दिमागी पहेलियां और ट्रिक्स",
    format: "riddle",
    hot: true,
    hotRank: 7,
    emoji: "🧩",
    tint: "#F3E8FF",
    border: "#E9D5FF",
    questionCount: 20,
    plays: 15300,
    coverImage: "https://images.unsplash.com/photo-1509228468518-180dd4864904?w=600&auto=format&fit=crop&q=80",
    description: "Sharpen your mind with clever logic riddles, wordplay and lateral thinking traps.",
    descriptionHi: "चतुर पहेलियों और तार्किक सवालों से अपने दिमाग की कसरत करें।",
    questions: [
      {
        id: "rbt-1",
        difficulty: "easy",
        text: "I speak without a mouth and hear without ears. I have no body, but I come alive with wind. What am I?",
        textHi: "बिना मुंह के बोलता हूं, बिना कान के सुनता हूं। शरीर नहीं है फिर भी हवा से जीवंत हो उठता हूं। मैं कौन हूं?",
        optionLayout: "text",
        options: ["An Echo", "A Cloud", "A Shadow", "A Whisper"],
        optionsHi: ["गूंज (इको)", "बादल", "परछाई", "फुसफुसाहट"],
        correctIndex: 0,
        explanation: "An echo bounces back your own voice when sound waves hit reflective surfaces.",
        explanationHi: "गूंज (Echo) ध्वनि तरंगों के परावर्तन से उत्पन्न होती है।",
      },
      {
        id: "rbt-2",
        difficulty: "medium",
        text: "The more of this there is, the less you see. What is it?",
        textHi: "यह जितना अधिक होता है, उतना ही कम दिखाई देता है। यह क्या है?",
        optionLayout: "text",
        options: ["Darkness", "Light", "Rain", "Fog"],
        optionsHi: ["अंधेरा", "रोशनी", "बारिश", "धुंध"],
        correctIndex: 0,
        explanation: "In total darkness, visibility drops to zero.",
        explanationHi: "अंधेरा जितना गहरा होता है, दृश्यता उतनी ही कम हो जाती है।",
      },
    ],
  },
  {
    id: "true-or-false-facts",
    slug: "true-or-false-facts",
    title: "True or False Facts",
    titleHi: "सच या झूठ रोचक तथ्य",
    format: "fact",
    hot: true,
    hotRank: 8,
    emoji: "💡",
    tint: "#E0F2FE",
    border: "#BAE6FD",
    questionCount: 20,
    plays: 13700,
    coverImage: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=600&auto=format&fit=crop&q=80",
    description: "Test your intuition on bizarre facts, scientific realities and historic myths.",
    descriptionHi: "अजीबोगरीब वैज्ञानिक तथ्यों और ऐतिहासिक मान्यताओं पर अपनी समझ को परखें।",
    questions: [
      {
        id: "tof-1",
        difficulty: "easy",
        text: "True or False: Honey never spoils and edible honey has been found in ancient Egyptian tombs.",
        textHi: "सच या झूठ: शहद कभी खराब नहीं होता और प्राचीन मिस्र के मकबरों में हजारों साल पुराना खाने योग्य शहद मिला है।",
        optionLayout: "text",
        options: ["True", "False"],
        optionsHi: ["सच (True)", "झूठ (False)"],
        correctIndex: 0,
        explanation: "Honey has low moisture and high acidity, making it impossible for bacteria to thrive.",
        explanationHi: "शहद में नमी बहुत कम और अम्लीयता अधिक होती है जिससे बैक्टीरिया नहीं पनप पाते।",
      },
      {
        id: "tof-2",
        difficulty: "easy",
        text: "True or False: Bananas are naturally radioactive due to high potassium content.",
        textHi: "सच या झूठ: पोटैशियम की अधिक मात्रा के कारण केले स्वाभाविक रूप से हल्के रेडियोधर्मी होते हैं।",
        optionLayout: "text",
        options: ["True", "False"],
        optionsHi: ["सच (True)", "झूठ (False)"],
        correctIndex: 0,
        explanation: "Bananas contain Potassium-40, a naturally occurring radioactive isotope, but in entirely harmless amounts.",
        explanationHi: "केले में पोटैशियम-40 आइसोटोप होता है जो स्वाभाविक रूप से पूरी तरह हानिरहित स्तर पर रेडियोधर्मी होता है।",
      },
    ],
  },
];
