// src/lib/mainCategoriesConfig.js

/**
 * 40 Canonical Main Categories (Step 3: Declutter Customer Web & Self-Explanatory Browsing)
 * Level 1 Taxonomy for QuizWeb.
 */

export const MAIN_CATEGORIES = [
  {
    id: 1,
    slug: "india-gk",
    name: "India GK",
    nameHi: "भारत सामान्य ज्ञान",
    icon: "🇮🇳",
    example: "Indian History, Polity, Science",
    chip: "india-gk",
    description: "Explore the comprehensive trivia, heritage, politics, and achievements of India.",
    descriptionHi: "भारतीय इतिहास, राजनीति, संविधान, विज्ञान, संस्कृति और उपलब्धियों का विस्तृत क्विज़ संग्रह।",
    subcategories: [
      { name: "Indian History", slug: "indian-history", topics: ["Ancient India", "Medieval India", "Modern India", "Post-Independence"] },
      { name: "Indian Geography", slug: "indian-geography", topics: ["Rivers & Lakes", "Mountains & Hills", "Climate & Soil", "Natural Resources"] },
      { name: "Indian Polity", slug: "indian-polity", topics: ["Constitution", "Parliament", "Supreme Court", "Fundamental Rights"] },
      { name: "Indian Economy", slug: "indian-economy", topics: ["Banking & RBI", "Budget & Taxes", "Economic History", "Industry"] },
      { name: "Indian Culture", slug: "indian-culture", topics: ["Festivals", "Dances", "Folk Traditions", "Costumes"] },
      { name: "Indian Science", slug: "indian-science", topics: ["ISRO & Space", "Nuclear Research", "Scientists", "Inventions"] },
      { name: "Indian Sports", slug: "indian-sports", topics: ["Cricket History", "Olympics", "Hockey", "Indigenous Games"] },
      { name: "Indian Awards", slug: "indian-awards", topics: ["Bharat Ratna", "Padma Awards", "Gallantry Awards", "Sahitya Akademi"] },
      { name: "Indian Defence", slug: "indian-defence", topics: ["Indian Army", "Indian Navy", "Air Force", "Missiles & Tech"] },
      { name: "Indian Railways", slug: "indian-railways", topics: ["Railway History", "Zones & Trains", "Vande Bharat", "Tech"] },
    ],
  },
  {
    id: 2,
    slug: "world-gk",
    name: "World GK",
    nameHi: "विश्व सामान्य ज्ञान",
    icon: "🌍",
    example: "Countries, Capitals, World History",
    chip: "all",
    description: "Global knowledge covering continents, nations, international organizations, and records.",
    descriptionHi: "विश्व के देश, राजधानियां, मुद्राएं, संयुक्त राष्ट्र, वैश्विक इतिहास और भूगोल।",
    subcategories: [
      { name: "World Geography", slug: "world-geography", topics: ["Continents", "Oceans & Seas", "Capitals & Currencies", "World Mountains"] },
      { name: "World History", slug: "world-history", topics: ["Ancient Civilizations", "World Wars", "Renaissance", "Great Empires"] },
      { name: "World Organizations", slug: "world-organizations", topics: ["United Nations", "WHO", "UNESCO", "World Bank & IMF"] },
      { name: "World Records", slug: "world-records", topics: ["Highest & Longest", "First in the World", "Guinness Records"] },
      { name: "Famous World Leaders", slug: "world-leaders", topics: ["Historical Figures", "Statesmen", "Nobel Laureates"] },
    ],
  },
  {
    id: 3,
    slug: "indian-geography",
    name: "Indian Geography",
    nameHi: "भारतीय भूगोल",
    icon: "🗺️",
    example: "States, Rivers, Mountains",
    chip: "states",
    description: "Himalayas, peninsular rivers, monsoon patterns, soil types, and regional geography.",
    descriptionHi: "भारत की नदियां, पर्वतमालाएं, जलवायु, मिट्टी, राष्ट्रीय उद्यान और प्राकृतिक संपदा।",
    subcategories: [
      { name: "Himalayan & Peninsular Rivers", slug: "rivers", topics: ["Ganga Basin", "Indus System", "Godavari & Krishna", "Narmada & Tapi"] },
      { name: "Mountains & Plateaus", slug: "mountains", topics: ["Himalayas", "Western Ghats", "Eastern Ghats", "Deccan Plateau"] },
      { name: "Climate & Monsoon", slug: "climate", topics: ["Southwest Monsoon", "Winter Rains", "Cyclones", "Rainfall Zones"] },
      { name: "Forests & Wildlife Reserves", slug: "forests-parks", topics: ["National Parks", "Tiger Reserves", "Bird Sanctuaries", "Wetlands"] },
    ],
  },
  {
    id: 4,
    slug: "indian-cities",
    name: "Indian Cities",
    nameHi: "भारत के प्रमुख शहर",
    icon: "🏙️",
    example: "Mumbai, Delhi, Indore, Jaipur",
    chip: "cities",
    description: "Famous urban hubs, metropolitan culture, food, landmarks, and city histories.",
    descriptionHi: "इंदौर, मुंबई, दिल्ली, जयपुर, बेंगलुरु सहित भारत के प्रमुख शहरों का इतिहास, संस्कृति और पहचान।",
    subcategories: [
      { name: "Mega Metros", slug: "metros", topics: ["Delhi NCR", "Mumbai", "Bengaluru", "Kolkata", "Chennai", "Hyderabad"] },
      { name: "Heritage & Cultural Cities", slug: "heritage-cities", topics: ["Varanasi", "Jaipur", "Udaipur", "Amritsar", "Madurai"] },
      { name: "Clean & Smart Cities", slug: "smart-cities", topics: ["Indore", "Surat", "Bhopal", "Chandigarh", "Pune"] },
    ],
  },
  {
    id: 5,
    slug: "indian-states-uts",
    name: "Indian States & UTs",
    nameHi: "भारतीय राज्य व केंद्र शासित प्रदेश",
    icon: "🏛️",
    example: "Rajasthan, MP, Kerala",
    chip: "states",
    description: "Dedicated quizzes for each of India's 28 states and 8 union territories.",
    descriptionHi: "राजस्थान, मध्य प्रदेश, उत्तर प्रदेश, केरल सहित सभी 28 राज्यों और 8 केंद्र शासित प्रदेशों का विशेष ज्ञान।",
    subcategories: [
      { name: "Northern States", slug: "north-india", topics: ["Uttar Pradesh", "Rajasthan", "Punjab", "Haryana", "Himachal Pradesh", "Uttarakhand"] },
      { name: "Central & Western States", slug: "central-west-india", topics: ["Madhya Pradesh", "Maharashtra", "Gujarat", "Chhattisgarh", "Goa"] },
      { name: "Southern States", slug: "south-india", topics: ["Tamil Nadu", "Karnataka", "Kerala", "Andhra Pradesh", "Telangana"] },
      { name: "Eastern & North-Eastern States", slug: "east-northeast-india", topics: ["Bihar", "West Bengal", "Odisha", "Assam", "Sikkim", "Seven Sisters"] },
      { name: "Union Territories", slug: "union-territories", topics: ["Delhi", "Jammu & Kashmir", "Ladakh", "Puducherry", "Andaman & Nicobar", "Chandigarh"] },
    ],
  },
  {
    id: 6,
    slug: "religion-spirituality",
    name: "Religion & Spirituality",
    nameHi: "धर्म और आध्यात्म",
    icon: "🙏",
    example: "Hinduism, Buddhism, Jainism",
    chip: "all",
    description: "Sacred scriptures, epics, deities, philosophical schools, festivals, and world religions.",
    descriptionHi: "रामायण, महाभारत, वेद, उपनिषद, बौद्ध, जैन, सिख व विश्व धर्मों का पावन ज्ञान।",
    subcategories: [
      { name: "Hinduism & Epics", slug: "hinduism", topics: ["Ramayana", "Mahabharata", "Vedas & Upanishads", "Bhagavad Gita", "Puranas"] },
      { name: "Buddhism & Jainism", slug: "buddhism-jainism", topics: ["Lord Buddha & Teachings", "Tirthankaras", "Mahavira", "Sacred Sites"] },
      { name: "Sikhism & Gurus", slug: "sikhism", topics: ["Ten Sikh Gurus", "Guru Granth Sahib", "Golden Temple", "Festivals"] },
      { name: "World Religions", slug: "world-religions", topics: ["Islam", "Christianity", "Judaism", "Zoroastrianism"] },
    ],
  },
  {
    id: 7,
    slug: "entertainment",
    name: "Entertainment",
    nameHi: "मनोरंजन व सिनेमा",
    icon: "🎬",
    example: "Bollywood, Movies, TV",
    chip: "cinema",
    description: "Bollywood, regional Indian cinema, Hollywood, famous dialogues, actors, and TV series.",
    descriptionHi: "बॉलीवुड, दक्षिण भारतीय सिनेमा, हॉलीवुड, प्रसिद्ध डायलॉग्स, गाने और अभिनेता।",
    subcategories: [
      { name: "Bollywood Cinema", slug: "bollywood", topics: ["Classic Movies", "Iconic Dialogues", "Superstars", "Music Directors"] },
      { name: "Regional Indian Cinema", slug: "regional-cinema", topics: ["South Cinema (Tollywood, Kollywood)", "Bengali Cinema", "Marathi Cinema"] },
      { name: "Hollywood & Global Film", slug: "hollywood", topics: ["Oscar Winners", "Blockbusters", "Franchises (Marvel, DC)", "Directors"] },
      { name: "TV Shows & Web Series", slug: "shows-series", topics: ["Indian Television", "OTT Web Series", "Reality Shows", "Sitcoms"] },
    ],
  },
  {
    id: 8,
    slug: "music",
    name: "Music",
    nameHi: "संगीत व वाद्य",
    icon: "🎵",
    example: "Bollywood, Classical, International",
    chip: "cinema",
    description: "Indian classical ragas, legendary singers, folk rhythms, and world musical instruments.",
    descriptionHi: "भारतीय शास्त्रीय संगीत, राग, वादक, पार्श्वगायक और अंतर्राष्ट्रीय संगीत।",
    subcategories: [
      { name: "Indian Classical Music", slug: "classical-music", topics: ["Hindustani Music", "Carnatic Music", "Ragas & Taals", "Gharanas"] },
      { name: "Playback Singers & Composers", slug: "playback-singers", topics: ["Lata Mangeshkar", "Kishore Kumar", "A.R. Rahman", "RD Burman"] },
      { name: "Musical Instruments", slug: "instruments", topics: ["String (Sitar, Sarod)", "Percussion (Tabla, Mridangam)", "Wind (Flute, Shehnai)"] },
    ],
  },
  {
    id: 9,
    slug: "sports",
    name: "Sports",
    nameHi: "खेलकूद",
    icon: "🏏",
    example: "Cricket, Football, Olympics",
    chip: "sports",
    description: "Cricket, IPL, football world cups, Olympics, badminton, hockey, chess, and athletic legends.",
    descriptionHi: "क्रिकेट, आईपीएल, फुटबॉल, ओलंपिक, बैडमिंटन, शतरंज और खेल इतिहास।",
    subcategories: [
      { name: "Cricket & IPL", slug: "cricket", topics: ["World Cups", "IPL Records", "Indian Cricket Legends", "Test Cricket", "T20 Trivia"] },
      { name: "Football & Leagues", slug: "football", topics: ["FIFA World Cup", "UEFA Champions League", "Messi & Ronaldo", "ISL"] },
      { name: "Olympics & Athletics", slug: "olympics", topics: ["Olympic History", "Indian Medalists", "Track & Field", "Paralympics"] },
      { name: "Racket & Board Sports", slug: "other-sports", topics: ["Badminton", "Tennis Grand Slams", "Chess Grandmasters", "Hockey"] },
    ],
  },
  {
    id: 10,
    slug: "science",
    name: "Science",
    nameHi: "विज्ञान",
    icon: "🔬",
    example: "Physics, Chemistry, Biology",
    chip: "science",
    description: "Fundamental laws of nature, chemical elements, human biology, genetics, and modern discovery.",
    descriptionHi: "भौतिक विज्ञान, रसायन विज्ञान, जीव विज्ञान, मानव शरीर और वैज्ञानिक नियम।",
    subcategories: [
      { name: "Physics", slug: "physics", topics: ["Mechanics & Motion", "Optics & Light", "Electricity & Magnetism", "Thermodynamics", "Modern Physics"] },
      { name: "Chemistry", slug: "chemistry", topics: ["Periodic Table", "Chemical Reactions", "Acids & Bases", "Organic Compounds", "Everyday Chemistry"] },
      { name: "Biology & Life Sciences", slug: "biology", topics: ["Human Anatomy", "Cell Biology", "Genetics & DNA", "Plant Physiology", "Ecology"] },
      { name: "Earth & Atmospheric Science", slug: "earth-science", topics: ["Geology", "Atmosphere & Weather", "Oceanography", "Fossils"] },
    ],
  },
  {
    id: 11,
    slug: "technology",
    name: "Technology",
    nameHi: "कंप्यूटर व तकनीक",
    icon: "💻",
    example: "Computers, AI, Internet",
    chip: "science",
    description: "Artificial intelligence, software, coding, smartphones, cybersecurity, and future tech.",
    descriptionHi: "कंप्यूटर, कृत्रिम बुद्धिमत्ता (AI), इंटरनेट, सॉफ्टवेयर, प्रोग्रामिंग और गैजेट्स।",
    subcategories: [
      { name: "Computers & Software", slug: "computers", topics: ["Operating Systems", "Programming Languages", "Hardware Basics", "Cloud Computing"] },
      { name: "AI & Modern Tech", slug: "ai-modern", topics: ["Artificial Intelligence", "Robotics", "Machine Learning", "Smartphones & Apps"] },
      { name: "Cybersecurity & Internet", slug: "cyber-internet", topics: ["Cyber Safety", "Networking Protocols", "Social Media", "Digital Payments"] },
    ],
  },
  {
    id: 12,
    slug: "space-astronomy",
    name: "Space & Astronomy",
    nameHi: "अंतरिक्ष व खगोल विज्ञान",
    icon: "🚀",
    example: "ISRO, NASA, Planets",
    chip: "space",
    description: "Planets of the solar system, galaxies, black holes, ISRO missions, NASA, and moon landings.",
    descriptionHi: "सौरमंडल, ग्रह, तारे, ब्लैक होल, इसरो मिशन, चंद्रयान, नासा और ब्रह्मांडीय रहस्य।",
    subcategories: [
      { name: "Solar System & Planets", slug: "solar-system", topics: ["The Sun", "Inner Planets", "Gas Giants", "Moons of the Solar System"] },
      { name: "Deep Space & Universe", slug: "deep-space", topics: ["Galaxies & Nebulae", "Black Holes", "Stars & Supernovas", "Big Bang"] },
      { name: "Space Agencies & Missions", slug: "space-missions", topics: ["ISRO (Chandrayaan, Mangalyaan)", "NASA (Apollo, Artemis)", "SpaceX", "James Webb Telescope"] },
    ],
  },
  {
    id: 13,
    slug: "history",
    name: "History",
    nameHi: "इतिहास",
    icon: "📜",
    example: "India, World, Civilizations",
    chip: "all",
    description: "Ancient empires, revolutions, world wars, freedom struggles, and historic milestones.",
    descriptionHi: "प्राचीन सभ्यताएं, मध्यकालीन सल्तनतें, आधुनिक क्रांतियां और विश्व इतिहास।",
    subcategories: [
      { name: "Ancient Civilizations", slug: "ancient-civ", topics: ["Indus Valley", "Mesopotamia", "Ancient Egypt", "Ancient Greece & Rome"] },
      { name: "Medieval Empires", slug: "medieval-empires", topics: ["Ottoman Empire", "Mongol Empire", "Byzantine Empire", "Holy Roman Empire"] },
      { name: "Modern World & Revolutions", slug: "modern-world", topics: ["French Revolution", "Industrial Revolution", "World War I & II", "Cold War"] },
    ],
  },
  {
    id: 14,
    slug: "geography",
    name: "Geography",
    nameHi: "विश्व भूगोल",
    icon: "🌎",
    example: "World Geography",
    chip: "all",
    description: "Physical geography, world mountains, deserts, straits, tectonic plates, and maps.",
    descriptionHi: "महाद्वीप, महासागर, जलसंधियां, मरुस्थल, ज्वालामुखी और स्थलाकृतियां।",
    subcategories: [
      { name: "Physical Geography", slug: "physical-geography", topics: ["Plate Tectonics", "Volcanoes & Earthquakes", "Glaciers & Deserts", "Atmosphere"] },
      { name: "World Water Bodies", slug: "water-bodies", topics: ["Major Rivers of World", "Great Lakes", "Straits & Canals", "Ocean Trenches"] },
      { name: "World Maps & Latitudes", slug: "cartography", topics: ["Equator & Tropics", "Time Zones", "Prime Meridian", "Map Projections"] },
    ],
  },
  {
    id: 15,
    slug: "general-knowledge",
    name: "General Knowledge",
    nameHi: "सामान्य ज्ञान (Mixed GK)",
    icon: "🧠",
    example: "Mixed GK",
    chip: "all",
    description: "All-round trivia, miscellaneous facts, general curiosity questions, and quick quizzes.",
    descriptionHi: "सर्वश्रेष्ठ मिश्रित सामान्य ज्ञान, महत्वपूर्ण तिथियां, संक्षिप्त नाम और रोचक तथ्य।",
    subcategories: [
      { name: "Static GK Highlights", slug: "static-gk", topics: ["First in World", "Largest & Smallest", "Important Days", "Headquarters"] },
      { name: "Curiosity & Trivia", slug: "curiosity-trivia", topics: ["Everyday Science Facts", "Human Wonders", "Odd & Unusual Facts"] },
    ],
  },
  {
    id: 16,
    slug: "current-affairs",
    name: "Current Affairs",
    nameHi: "करेंट अफेयर्स",
    icon: "📰",
    example: "India, World, Sports",
    chip: "all",
    description: "Latest national and international developments, summits, sports triumphs, and honors.",
    descriptionHi: "दैनिक समसामयिकी, राष्ट्रीय व अंतर्राष्ट्रीय घटनाक्रम, शिखर सम्मेलन और खेल जगत की ताज़ा खबरें।",
    subcategories: [
      { name: "National News", slug: "national-affairs", topics: ["Government Policies", "Appointments", "State Schemes", "Summits"] },
      { name: "International Affairs", slug: "international-affairs", topics: ["Global Treaties", "G20 & BRICS", "Bilateral Visits", "Global Conflicts"] },
      { name: "Sports & Awards Current", slug: "sports-awards-ca", topics: ["Recent Tournaments", "Current Honors", "Championship Winners"] },
    ],
  },
  {
    id: 17,
    slug: "business-economy",
    name: "Business & Economy",
    nameHi: "व्यापार व अर्थव्यवस्था",
    icon: "💰",
    example: "Banking, Finance, Companies",
    chip: "all",
    description: "Banking concepts, monetary policy, stock markets, startups, taxation, and corporate history.",
    descriptionHi: "बैंकिंग, शेयर बाजार, बजट, मुद्रास्फीति, जीएसटी, स्टार्टअप्स और प्रसिद्ध कंपनियां।",
    subcategories: [
      { name: "Banking & Finance", slug: "banking-finance", topics: ["RBI & Monetary Policy", "Types of Accounts", "Inflation & Repo Rate", "Financial Terms"] },
      { name: "Stock Market & Investments", slug: "stock-market", topics: ["NSE & BSE", "Mutual Funds", "IPO Basics", "Global Indices"] },
      { name: "Companies & Unicorns", slug: "companies-startups", topics: ["Indian Startups", "Tech Giants", "Famous CEOs", "Mergers & Acquisitions"] },
    ],
  },
  {
    id: 18,
    slug: "politics-government",
    name: "Politics & Government",
    nameHi: "राजनीति व शासन",
    icon: "⚖️",
    example: "Constitution, Parliament, Elections",
    chip: "all",
    description: "Constitutional articles, parliament sessions, democratic institutions, and prime ministers.",
    descriptionHi: "भारतीय संविधान, संसद, राष्ट्रपति, चुनाव आयोग, मौलिक अधिकार और प्रशासनिक व्यवस्था।",
    subcategories: [
      { name: "Constitution & Law", slug: "constitution", topics: ["Preamble & Articles", "Fundamental Rights", "Constitutional Amendments", "Judiciary"] },
      { name: "Parliament & Executive", slug: "parliament-executive", topics: ["Lok Sabha & Rajya Sabha", "President & Prime Minister", "Cabinet Ministries"] },
      { name: "Elections & Governance", slug: "elections-governance", topics: ["Election Commission", "EVM & Voting", "State Legislatures", "Panchayati Raj"] },
    ],
  },
  {
    id: 19,
    slug: "environment-nature",
    name: "Environment & Nature",
    nameHi: "पर्यावरण व प्रकृति",
    icon: "🌿",
    example: "Wildlife, Climate, Ecology",
    chip: "science",
    description: "Biodiversity conservation, climate action, ecosystems, global warming, and green living.",
    descriptionHi: "पर्यावरण संरक्षण, पारिस्थितिकी तंत्र, जलवायु परिवर्तन, प्रदूषण नियंत्रण और जैव विविधता।",
    subcategories: [
      { name: "Ecology & Ecosystems", slug: "ecology", topics: ["Food Chains", "Biomes", "Biodiversity Hotspots", "Ozone Layer"] },
      { name: "Climate Change & Action", slug: "climate-change", topics: ["Global Warming", "Paris Agreement", "Renewable Energy", "Carbon Footprint"] },
      { name: "Conservation & Sanctuaries", slug: "conservation", topics: ["Endangered Species", "Project Tiger", "Ramsar Sites", "Forest Acts"] },
    ],
  },
  {
    id: 20,
    slug: "food-cuisine",
    name: "Food & Cuisine",
    nameHi: "खानपान व व्यंजन",
    icon: "🍛",
    example: "Indian Food, World Food",
    chip: "all",
    description: "Traditional regional delicacies, street food classics, spices, and international culinary arts.",
    descriptionHi: "भारतीय प्रांतीय व्यंजन, मिठाइयां, मसाले, स्ट्रीट फूड और वैश्विक खानपान।",
    subcategories: [
      { name: "Indian Regional Cuisines", slug: "indian-cuisine", topics: ["North Indian Curries", "South Indian Tiffins", "Bengali Sweets", "Gujarati & Rajasthani Thali"] },
      { name: "Spices & Food Science", slug: "spices-science", topics: ["Indian Spices", "Nutritional Value", "Herbs", "Cooking Techniques"] },
      { name: "World Food & Beverages", slug: "world-food", topics: ["Italian & Mediterranean", "Asian Cuisines", "Coffee & Tea Cultures", "Desserts"] },
    ],
  },
  {
    id: 21,
    slug: "literature",
    name: "Literature",
    nameHi: "साहित्य व पुस्तकें",
    icon: "📚",
    example: "Books, Authors, Poetry",
    chip: "all",
    description: "Celebrated authors, classic novels, poetic masterpieces, epics, and literary prizes.",
    descriptionHi: "प्रसिद्ध लेखक, कालजयी उपन्यास, कविताएं, ज्ञानपीठ पुरस्कार और विश्व साहित्य।",
    subcategories: [
      { name: "Indian Literature", slug: "indian-literature", topics: ["Hindi Sahitya (Premchand, Nirala)", "Tagore Works", "Sanskrit Classics", "Modern Indian Authors"] },
      { name: "World Classics", slug: "world-literature", topics: ["Shakespeare Plays", "Russian Classics", "American Literature", "European Novels"] },
      { name: "Literary Awards & Epics", slug: "literary-awards", topics: ["Booker Prize", "Nobel in Literature", "Jnanpith Award", "Great Epics"] },
    ],
  },
  {
    id: 22,
    slug: "language-grammar",
    name: "Language & Grammar",
    nameHi: "भाषा व व्याकरण",
    icon: "🔤",
    example: "English, Hindi, Languages",
    chip: "all",
    description: "Vocabulary booster, Hindi vyakaran, English grammar rules, idioms, and language roots.",
    descriptionHi: "हिंदी व्याकरण (संधि, समास), अंग्रेजी ग्रामर, शब्दावली, मुहावरे और विश्व भाषाएं।",
    subcategories: [
      { name: "English Grammar & Vocabulary", slug: "english-grammar", topics: ["Parts of Speech", "Tenses & Modals", "Idioms & Phrases", "Vocabulary Builder"] },
      { name: "Hindi Vyakaran", slug: "hindi-vyakaran", topics: ["Varnamala & Sandhi", "Samas", "Muhavare & Lokoktiyan", "Alankar & Chhand"] },
      { name: "Linguistics & World Languages", slug: "world-languages", topics: ["Language Families", "Scripts & Alphabets", "Official Languages"] },
    ],
  },
  {
    id: 23,
    slug: "mathematics",
    name: "Mathematics",
    nameHi: "गणित",
    icon: "➗",
    example: "Arithmetic, Algebra, Geometry",
    chip: "all",
    description: "Mental arithmetic, speed math, algebra formulas, geometry theorems, and problem solving.",
    descriptionHi: "अंकगणित, बीजगणित, रेखागणित, संख्या पद्धति और रोचक गणितीय पहेलियां।",
    subcategories: [
      { name: "Arithmetic Proficiency", slug: "arithmetic", topics: ["Percentages & Averages", "Profit & Loss", "Time, Speed & Distance", "Simple & Compound Interest"] },
      { name: "Algebra & Number Systems", slug: "algebra", topics: ["Linear Equations", "Quadratic Equations", "Divisibility Rules", "LCM & HCF"] },
      { name: "Geometry & Mensuration", slug: "geometry-mensuration", topics: ["Triangles & Circles", "Perimeter & Area", "Volume of 3D Solids", "Pythagoras Theorem"] },
    ],
  },
  {
    id: 24,
    slug: "reasoning-brain-games",
    name: "Reasoning & Brain Games",
    nameHi: "तर्कशक्ति व पहेलियां",
    icon: "🧩",
    example: "Logic, Puzzles, Riddles",
    chip: "fun",
    description: "Logical deduction, verbal reasoning, pattern recognition, spatial puzzles, and brain workouts.",
    descriptionHi: "तार्किक तर्कशक्ति, कोडिंग-डिकोडिंग, दिशा ज्ञान, ब्लड रिलेशन और पहेलियां।",
    subcategories: [
      { name: "Logical Deduction", slug: "logical-reasoning", topics: ["Syllogisms", "Blood Relations", "Direction Sense", "Seating Arrangements"] },
      { name: "Verbal & Pattern Reasoning", slug: "pattern-reasoning", topics: ["Series Completion", "Coding-Decoding", "Analogy", "Odd One Out"] },
      { name: "Brain Teasers & Riddles", slug: "riddles-puzzles", topics: ["Math Puzzles", "Lateral Thinking", "Classic Riddles", "IQ Teasers"] },
    ],
  },
  {
    id: 25,
    slug: "art-culture",
    name: "Art & Culture",
    nameHi: "कला व संस्कृति",
    icon: "🎨",
    example: "Dance, Painting, Architecture",
    chip: "all",
    description: "Classical dance forms, traditional painting styles, sculptures, and living cultural heritage.",
    descriptionHi: "शास्त्रीय नृत्य (कथक, भरतनाट्यम), लोक कलाएं, चित्रकला (मधुबनी, वरली) और स्थापत्य।",
    subcategories: [
      { name: "Classical & Folk Dances", slug: "dances", topics: ["8 Classical Dances", "Bhangra & Giddha", "Garba & Dandiya", "Bihu & Lavani"] },
      { name: "Painting & Handicrafts", slug: "paintings-crafts", topics: ["Madhubani Painting", "Warli Art", "Pattachitra", "Textiles (Banarasi, Kanjeevaram)"] },
      { name: "Temple Architecture", slug: "architecture", topics: ["Nagara Style", "Dravida Style", "Vesara Style", "Buddhist Stupas"] },
    ],
  },
  {
    id: 26,
    slug: "heritage-monuments",
    name: "Heritage & Monuments",
    nameHi: "धरोहर व स्मारक",
    icon: "🏺",
    example: "Forts, Temples, UNESCO",
    chip: "all",
    description: "UNESCO World Heritage sites, majestic forts, rock-cut caves, and timeless architectural wonders.",
    descriptionHi: "यूनेस्को विश्व धरोहर स्थल, ऐतिहासिक किले, गुफाएं, मंदिर और प्राचीन स्मारक।",
    subcategories: [
      { name: "UNESCO World Heritage India", slug: "unesco-sites", topics: ["Taj Mahal & Agra Fort", "Ajanta & Ellora Caves", "Hampi Ruins", "Khajuraho Temples"] },
      { name: "Forts & Palaces", slug: "forts-palaces", topics: ["Red Fort", "Amer Fort", "Chittorgarh", "Gwalior Fort", "Mysore Palace"] },
      { name: "Ancient & Medieval Marvels", slug: "ancient-marvels", topics: ["Qutub Minar", "Konark Sun Temple", "Brihadeeswarar Temple", "Sanchi Stupa"] },
    ],
  },
  {
    id: 27,
    slug: "famous-people",
    name: "Famous People",
    nameHi: "महान व्यक्तित्व",
    icon: "🧑",
    example: "Leaders, Scientists, Actors",
    chip: "all",
    description: "Visionary thinkers, freedom fighters, transformative scientists, and icons of history.",
    descriptionHi: "महात्मा गांधी, डॉ. कलाम, स्वामी विवेकानंद, अल्बर्ट आइंस्टीन सहित युगप्रवर्तक महापुरुष।",
    subcategories: [
      { name: "Indian Freedom Fighters", slug: "freedom-fighters", topics: ["Mahatma Gandhi", "Bhagat Singh", "Subhas Chandra Bose", "Sardar Patel"] },
      { name: "Visionaries & Thinkers", slug: "visionaries", topics: ["Dr. APJ Abdul Kalam", "Swami Vivekananda", "Dr. BR Ambedkar", "Rabindranath Tagore"] },
      { name: "Global Pioneers", slug: "global-pioneers", topics: ["Albert Einstein", "Isaac Newton", "Nelson Mandela", "Marie Curie"] },
    ],
  },
  {
    id: 28,
    slug: "transport",
    name: "Transport",
    nameHi: "परिवहन व आवागमन",
    icon: "🚆",
    example: "Railways, Aviation, Roads",
    chip: "all",
    description: "Indian Railways network, aviation achievements, national highways, and automotive trivia.",
    descriptionHi: "भारतीय रेल नेटवर्क, विमानन, राष्ट्रीय राजमार्ग, मेट्रो प्रणाली और ऑटोमोबाइल।",
    subcategories: [
      { name: "Indian Railways Network", slug: "railways-network", topics: ["Railway Zones & Headquarters", "Mountain Railways", "Express Trains", "Railway Technology"] },
      { name: "Aviation & Airports", slug: "aviation", topics: ["Major Airports of India", "Airlines History", "Aviation Pioneers"] },
      { name: "Roadways & Vehicles", slug: "roadways", topics: ["National Highway Corridors", "Expressways", "Automobile Icons", "Bridges & Tunnels"] },
    ],
  },
  {
    id: 29,
    slug: "defence-military",
    name: "Defence & Military",
    nameHi: "रक्षा व सैन्य बल",
    icon: "🪖",
    example: "Indian Defence, Weapons history",
    chip: "all",
    description: "Indian Armed Forces, strategic missile programs, famous battles, and defense academies.",
    descriptionHi: "भारतीय सेना, नौसेना, वायुसेना, शौर्य पदक, मिसाइल कार्यक्रम और युद्ध इतिहास।",
    subcategories: [
      { name: "Armed Forces Structure", slug: "armed-forces", topics: ["Indian Army Commands", "Indian Navy Fleets", "Indian Air Force Squadrons", "Paramilitary Forces"] },
      { name: "Missiles & Indigenous Tech", slug: "defence-tech", topics: ["BrahMos", "Agni & Prithvi", "Tejas Fighter Aircraft", "INS Vikrant"] },
      { name: "Battles & Gallantry", slug: "battles-gallantry", topics: ["Param Vir Chakra Heroes", "1971 Liberation War", "Kargil Conflict", "Historical Battles"] },
    ],
  },
  {
    id: 30,
    slug: "awards-achievements",
    name: "Awards & Achievements",
    nameHi: "पुरस्कार व सम्मान",
    icon: "🏆",
    example: "Nobel, Oscars, Bharat Ratna",
    chip: "all",
    description: "Nobel laureates, Bharat Ratna honorees, Academy Awards, and premier civilian recognitions.",
    descriptionHi: "भारत रत्न, पद्म पुरस्कार, नोबेल पुरस्कार, ऑस्कर, ग्रैमी और खेल रत्न सम्मान।",
    subcategories: [
      { name: "National Civilian Awards", slug: "civilian-awards", topics: ["Bharat Ratna Recipients", "Padma Vibhushan", "Padma Bhushan & Shri"] },
      { name: "International Prestigious Honors", slug: "international-honors", topics: ["Nobel Prize History", "Academy Awards (Oscars)", "Pulitzer Prize", "Magsaysay Award"] },
      { name: "Sports & Culture Honors", slug: "sports-culture-awards", topics: ["Khel Ratna Award", "Arjuna Award", "Dadasaheb Phalke Award"] },
    ],
  },
  {
    id: 31,
    slug: "brands-companies",
    name: "Brands & Companies",
    nameHi: "ब्रांड्स व कंपनियां",
    icon: "🌐",
    example: "Indian & Global Companies",
    chip: "all",
    description: "Corporate empires, brand taglines, logo origins, business dynasties, and startup founders.",
    descriptionHi: "टाटा, रिलायंस, इंफोसिस, गूगल, ऐप्पल सहित भारतीय व वैश्विक ब्रांड्स का इतिहास व टैगलाइन।",
    subcategories: [
      { name: "Indian Corporate Giants", slug: "indian-corporates", topics: ["Tata Group", "Reliance Industries", "Infosys & Wipro", "Mahindra & Birla"] },
      { name: "Global Tech & Retail", slug: "global-brands", topics: ["Apple & Microsoft", "Google & Amazon", "Nike & Adidas", "Automobile Brands"] },
      { name: "Logos & Taglines Trivia", slug: "logos-taglines", topics: ["Famous Brand Taglines", "Logo Origins", "Brand Mascots"] },
    ],
  },
  {
    id: 32,
    slug: "lifestyle-everyday-knowledge",
    name: "Lifestyle & Everyday Knowledge",
    nameHi: "दैनिक जीवन व उपयोगी ज्ञान",
    icon: "🛍️",
    example: "Shopping, Home, Daily life",
    chip: "all",
    description: "Consumer awareness, home science, hygiene, traffic signs, first aid, and life skills.",
    descriptionHi: "स्वास्थ्य, पोषण, उपभोक्ता अधिकार, सड़क सुरक्षा, प्राथमिक चिकित्सा और उपयोगी दैनिक तथ्य।",
    subcategories: [
      { name: "Health, Wellness & First Aid", slug: "health-wellness", topics: ["Vitamins & Nutrition", "First Aid Essentials", "Mental Well-being", "Yoga"] },
      { name: "Everyday Law & Consumer Rights", slug: "consumer-rights", topics: ["Consumer Protection Act", "Banking Safety", "Cyber Hygiene"] },
      { name: "Civic Sense & Traffic Signs", slug: "civic-sense", topics: ["Traffic Rules & Signs", "Waste Segregation", "Public Etiquette"] },
    ],
  },
  {
    id: 33,
    slug: "gaming",
    name: "Gaming",
    nameHi: "गेमिंग व ई-स्पोर्ट्स",
    icon: "🎮",
    example: "Video Games, Esports",
    chip: "fun",
    description: "Video game legends, console evolutions, mobile gaming crazes, and competitive esports.",
    descriptionHi: "वीडियो गेम्स का इतिहास, मारियो, पबजी, जीटीए, ई-स्पोर्ट्स और गेमिंग कैरेक्टर्स।",
    subcategories: [
      { name: "Iconic Video Games", slug: "iconic-games", topics: ["Super Mario & Nintendo", "GTA Series", "Minecraft", "Pokemon Franchise"] },
      { name: "Mobile Gaming & Esports", slug: "mobile-esports", topics: ["BGMI & Free Fire", "Esports Tournaments", "Gaming Consoles (PlayStation, Xbox)"] },
    ],
  },
  {
    id: 34,
    slug: "animals-wildlife",
    name: "Animals & Wildlife",
    nameHi: "पशु-पक्षी व वन्यजीव",
    icon: "🦁",
    example: "Animals, Birds, Marine Life",
    chip: "science",
    description: "Fascinating mammals, bird migrations, ocean depths, venomous reptiles, and animal superpowers.",
    descriptionHi: "वन्यजीव, पक्षी, समुद्री जीव, विलुप्त प्राणी और पशु जगत की आश्चर्यजनक बातें।",
    subcategories: [
      { name: "Mammals & Big Cats", slug: "mammals-big-cats", topics: ["Tigers & Lions", "Elephants", "Whales & Dolphins", "Primate Intelligence"] },
      { name: "Avian Wonders (Birds)", slug: "birds", topics: ["Migratory Birds", "Flightless Birds", "Birds of Prey", "State Birds of India"] },
      { name: "Marine & Reptile Life", slug: "marine-reptiles", topics: ["Coral Reefs", "Sharks & Octopuses", "Crocodiles & Snakes", "Amphibians"] },
    ],
  },
  {
    id: 35,
    slug: "plants-agriculture",
    name: "Plants & Agriculture",
    nameHi: "पेड़-पौधे व कृषि",
    icon: "🌱",
    example: "Crops, Plants, Farming",
    chip: "science",
    description: "Medicinal flora, agricultural revolutions, cash crops, botanical wonders, and organic farming.",
    descriptionHi: "भारतीय फसलें (रबी, खरीफ), औषधीय पौधे, हरित क्रांति, वनस्पति शास्त्र और खेती।",
    subcategories: [
      { name: "Indian Agriculture & Crops", slug: "indian-agriculture", topics: ["Kharif & Rabi Crops", "Green Revolution", "Spices of India", "Cash Crops"] },
      { name: "Botanical Wonders & Trees", slug: "botany-trees", topics: ["Medicinal Plants (Neem, Tulsi)", "Carnivorous Plants", "Ancient Trees", "Photosynthesis"] },
    ],
  },
  {
    id: 36,
    slug: "inventions-discoveries",
    name: "Inventions & Discoveries",
    nameHi: "आविष्कार व खोजें",
    icon: "🧪",
    example: "Inventors, Discoveries",
    chip: "science",
    description: "Inventions that changed the world, pioneering scientists, serendipitous discoveries, and patents.",
    descriptionHi: "पहिया, बिजली, टेलीफोन, इंटरनेट, वैक्सीन सहित मानव इतिहास को बदलने वाले महान आविष्कार।",
    subcategories: [
      { name: "Everyday Inventions", slug: "everyday-inventions", topics: ["Electricity & Light Bulb", "Telephone & Radio", "Printing Press", "Internet & Web"] },
      { name: "Medical & Chemical Discoveries", slug: "medical-discoveries", topics: ["Penicillin & Antibiotics", "Vaccines", "X-Rays", "Anesthesia"] },
      { name: "Transport & Industrial Inventions", slug: "industrial-inventions", topics: ["Steam Engine", "Aeroplane", "Automobile", "Transistors"] },
    ],
  },
  {
    id: 37,
    slug: "travel-tourism",
    name: "Travel & Tourism",
    nameHi: "पर्यटन व यात्रा",
    icon: "✈️",
    example: "Destinations, Landmarks",
    chip: "all",
    description: "Iconic world landmarks, Indian hill stations, beach escapes, pilgrimage circuits, and travel tips.",
    descriptionHi: "भारत के हिल स्टेशन, ऐतिहासिक पर्यटन स्थल, विश्व के 7 अजूबे और प्रसिद्ध यात्रा मार्ग।",
    subcategories: [
      { name: "Wonders of the World", slug: "world-wonders", topics: ["7 Wonders of Ancient World", "New 7 Wonders", "Iconic Towers & Bridges"] },
      { name: "Incredible India Destinations", slug: "india-travel", topics: ["Himalayan Hill Stations", "Goa & Coastal Retreats", "Spiritual Circuits", "Desert Safari"] },
    ],
  },
  {
    id: 38,
    slug: "theatre-performing-arts",
    name: "Theatre & Performing Arts",
    nameHi: "रंगमंच व नाट्य कला",
    icon: "🎭",
    example: "Drama, Theatre, Dance",
    chip: "all",
    description: "Folk theater traditions, Shakespearean drama, street plays, puppetry, and theatrical arts.",
    descriptionHi: "पारंपरिक लोक नाट्य (नौटंकी, जात्रा, यक्षगान), रंगमंच कलाकार और ऐतिहासिक नाटक।",
    subcategories: [
      { name: "Indian Folk Theatre", slug: "folk-theatre", topics: ["Nautanki & Swang", "Jatra & Bhavai", "Yakshagana & Kathakali", "Kathputli Puppetry"] },
      { name: "World Theatre & Dramatists", slug: "world-theatre", topics: ["Greek Tragedy", "Shakespearean Theatre", "Modern Playwrights", "Broadway Basics"] },
    ],
  },
  {
    id: 39,
    slug: "kids-family-quiz",
    name: "Kids & Family Quiz",
    nameHi: "बच्चे और परिवार क्विज़",
    icon: "🧒",
    example: "Kids GK, Family Trivia",
    chip: "fun",
    description: "Fun pictorial quizzes, cartoon characters, fairy tales, animal sounds, and gentle family trivia.",
    descriptionHi: "बच्चों के लिए आसान व सचित्र क्विज़, कार्टून, परियों की कहानियां और मजेदार पारिवारिक सवाल।",
    subcategories: [
      { name: "Picture & Animal Fun", slug: "picture-fun", topics: ["Baby Animals", "Animal Sounds", "Colors & Shapes", "Fruit & Veggie Guess"] },
      { name: "Toons, Tales & Stories", slug: "toons-stories", topics: ["Panchatantra Stories", "Disney & Cartoon Characters", "Superhero Trivia"] },
      { name: "Junior Brain Boosters", slug: "junior-brain", topics: ["Simple Math Fun", "Day & Night Science", "Our Body Basics"] },
    ],
  },
  {
    id: 40,
    slug: "fun-viral-quiz",
    name: "Fun & Viral Quiz",
    nameHi: "मजेदार व वायरल क्विज़",
    icon: "🎯",
    example: "Guessing, Picture Quiz, Fun Facts",
    chip: "fun",
    description: "Rapid-fire guessing games, emoji puzzles, 'Who Am I?' challenges, and viral curiosities.",
    descriptionHi: "चित्र पहचानो, इमोजी पहेलियां, रैपिड फायर, कौन हूं मैं?, क्या आप जानते हैं? और वायरल ट्रिविया।",
    subcategories: [
      { name: "Guessing Games", slug: "guessing-games", topics: ["Guess the Personality", "Guess the Place", "Guess the Logo", "Guess the Flag"] },
      { name: "Interactive Formats", slug: "interactive-formats", topics: ["Who Am I?", "Emoji Word Puzzle", "Odd One Out", "Rapid Fire Trivia"] },
      { name: "Did You Know? Curiosities", slug: "viral-curiosities", topics: ["Bizarre World Facts", "Mind-Blowing Science", "Myth Busters"] },
    ],
  },
];

/**
 * Curated quick filter chips for the homepage
 */
export const QUICK_FILTER_CHIPS = [
  { id: "all", label: "All", labelHi: "सभी", icon: "✨" },
  { id: "india-gk", label: "India GK", labelHi: "भारत GK", icon: "🇮🇳" },
  { id: "science", label: "Science", labelHi: "विज्ञान", icon: "🔬" },
  { id: "sports", label: "Sports", labelHi: "खेल", icon: "🏏" },
  { id: "cities", label: "Cities", labelHi: "शहर", icon: "🏙️" },
  { id: "states", label: "States", labelHi: "राज्य", icon: "🏛️" },
  { id: "cinema", label: "Cinema", labelHi: "सिनेमा", icon: "🎬" },
  { id: "space", label: "Space", labelHi: "अंतरिक्ष", icon: "🚀" },
  { id: "fun", label: "Fun Quizzes", labelHi: "मजेदार", icon: "🎯" },
];

/**
 * Helper to get a Main Category by its slug or id
 */
export function getMainCategoryBySlug(slug) {
  if (!slug) return null;
  const clean = String(slug).toLowerCase().trim();
  return (
    MAIN_CATEGORIES.find(
      (c) => c.slug === clean || c.name.toLowerCase() === clean || c.name.toLowerCase().replace(/[^a-z0-9]+/g, "-") === clean
    ) || null
  );
}

/**
 * Curated Quick Filter Chip Slug Mappings
 */
export const CHIP_CATEGORY_SLUGS = {
  all: null,
  "india-gk": [
    "india-gk",
    "indian-geography",
    "indian-cities",
    "indian-states-uts",
    "history",
    "politics-government",
    "art-culture",
    "heritage-monuments",
    "defence-military",
  ],
  science: [
    "science",
    "technology",
    "space-astronomy",
    "mathematics",
    "inventions-discoveries",
  ],
  sports: ["sports", "gaming"],
  cities: ["indian-cities", "travel-tourism"],
  states: ["indian-states-uts", "indian-geography"],
  cinema: ["entertainment", "music", "theatre-performing-arts"],
  space: ["space-astronomy", "science"],
  fun: ["fun-viral-quiz", "kids-family-quiz", "gaming", "reasoning-brain-games"],
};

export function filterCategoriesByChip(categories, chipId) {
  if (!chipId || chipId === "all") return categories;
  const targetSlugs = CHIP_CATEGORY_SLUGS[chipId];
  if (!targetSlugs) return categories;
  return categories.filter((c) => targetSlugs.includes(c.slug));
}

