
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.19.3
 * Query Engine version: c2990dca591cba766e3b7ef5d9e8a84796e47ab7
 */
Prisma.prismaVersion = {
  client: "6.19.3",
  engine: "c2990dca591cba766e3b7ef5d9e8a84796e47ab7"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.UserScalarFieldEnum = {
  id: 'id',
  name: 'name',
  email: 'email',
  emailVerified: 'emailVerified',
  image: 'image',
  nickname: 'nickname',
  avatar: 'avatar',
  pin: 'pin',
  sessionVersion: 'sessionVersion',
  lastLoginAt: 'lastLoginAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  isPro: 'isPro',
  proExpiresAt: 'proExpiresAt',
  purchasedPasses: 'purchasedPasses',
  factsReadCount: 'factsReadCount',
  tfAnsweredCount: 'tfAnsweredCount',
  proBadge: 'proBadge'
};

exports.Prisma.VerificationTokenScalarFieldEnum = {
  id: 'id',
  identifier: 'identifier',
  token: 'token',
  expires: 'expires'
};

exports.Prisma.AccountScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  type: 'type',
  provider: 'provider',
  providerAccountId: 'providerAccountId',
  refresh_token: 'refresh_token',
  access_token: 'access_token',
  expires_at: 'expires_at',
  token_type: 'token_type',
  scope: 'scope',
  id_token: 'id_token',
  session_state: 'session_state'
};

exports.Prisma.CategoryScalarFieldEnum = {
  id: 'id',
  topic: 'topic',
  emoji: 'emoji',
  description: 'description',
  categoryClass: 'categoryClass',
  hidden: 'hidden',
  image: 'image',
  storyText: 'storyText',
  storyImage: 'storyImage',
  originalLang: 'originalLang',
  isTrending: 'isTrending',
  chips: 'chips',
  sortOrder: 'sortOrder',
  showSubCategoriesOnHome: 'showSubCategoriesOnHome',
  parentId: 'parentId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.QuestionScalarFieldEnum = {
  id: 'id',
  text: 'text',
  options: 'options',
  correctAnswer: 'correctAnswer',
  difficulty: 'difficulty',
  image: 'image',
  categoryId: 'categoryId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.UserProgressScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  categoryId: 'categoryId',
  setIndex: 'setIndex',
  progress: 'progress',
  score: 'score',
  isComplete: 'isComplete',
  lastQuestionIndex: 'lastQuestionIndex',
  answersJson: 'answersJson',
  updatedAt: 'updatedAt',
  createdAt: 'createdAt'
};

exports.Prisma.FavouriteScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  questionId: 'questionId',
  createdAt: 'createdAt'
};

exports.Prisma.AdminAccountScalarFieldEnum = {
  id: 'id',
  username: 'username',
  passwordHash: 'passwordHash',
  displayName: 'displayName',
  role: 'role',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PendingTaskScalarFieldEnum = {
  id: 'id',
  adminId: 'adminId',
  actionType: 'actionType',
  entityType: 'entityType',
  entityId: 'entityId',
  payload: 'payload',
  status: 'status',
  reviewedBy: 'reviewedBy',
  reviewNote: 'reviewNote',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.AdminActivityLogScalarFieldEnum = {
  id: 'id',
  adminId: 'adminId',
  action: 'action',
  details: 'details',
  createdAt: 'createdAt'
};

exports.Prisma.SettingScalarFieldEnum = {
  id: 'id',
  key: 'key',
  value: 'value'
};

exports.Prisma.NavigationLinkScalarFieldEnum = {
  id: 'id',
  name: 'name',
  href: 'href',
  icon: 'icon',
  description: 'description',
  keywords: 'keywords',
  sortOrder: 'sortOrder',
  isVisible: 'isVisible',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.DailyQuizScalarFieldEnum = {
  id: 'id',
  type: 'type',
  date: 'date',
  categoryId: 'categoryId',
  questionIds: 'questionIds',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SectionScalarFieldEnum = {
  id: 'id',
  name: 'name',
  isVisible: 'isVisible',
  order: 'order',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SubSectionScalarFieldEnum = {
  id: 'id',
  name: 'name',
  isVisible: 'isVisible',
  order: 'order',
  quizIds: 'quizIds',
  sectionId: 'sectionId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SchoolBoardScalarFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  sortOrder: 'sortOrder',
  hidden: 'hidden',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SchoolClassScalarFieldEnum = {
  id: 'id',
  boardId: 'boardId',
  number: 'number',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SchoolSubjectScalarFieldEnum = {
  id: 'id',
  classId: 'classId',
  name: 'name',
  slug: 'slug',
  sortOrder: 'sortOrder',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SchoolChapterScalarFieldEnum = {
  id: 'id',
  subjectId: 'subjectId',
  title: 'title',
  sortOrder: 'sortOrder',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SchoolQuestionScalarFieldEnum = {
  id: 'id',
  chapterId: 'chapterId',
  type: 'type',
  prompt: 'prompt',
  options: 'options',
  answer: 'answer',
  explanation: 'explanation',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SchoolProgressScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  chapterId: 'chapterId',
  attempts: 'attempts',
  bestScore: 'bestScore',
  lastScore: 'lastScore',
  lastAttemptAt: 'lastAttemptAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CurrentAffairScalarFieldEnum = {
  id: 'id',
  date: 'date',
  category: 'category',
  heading: 'heading',
  description: 'description',
  image: 'image',
  hidden: 'hidden',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CoursePackageScalarFieldEnum = {
  id: 'id',
  board: 'board',
  class: 'class',
  name: 'name',
  price: 'price',
  bookCount: 'bookCount',
  images: 'images',
  description: 'description',
  hidden: 'hidden',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CourseOrderScalarFieldEnum = {
  id: 'id',
  packageId: 'packageId',
  parentName: 'parentName',
  childName: 'childName',
  board: 'board',
  class: 'class',
  deliveryAddress: 'deliveryAddress',
  contactNumber: 'contactNumber',
  isWhatsApp: 'isWhatsApp',
  totalAmount: 'totalAmount',
  status: 'status',
  paymentId: 'paymentId',
  userId: 'userId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PromoCodeScalarFieldEnum = {
  id: 'id',
  code: 'code',
  discountType: 'discountType',
  discountValue: 'discountValue',
  status: 'status',
  expiryDate: 'expiryDate',
  usageCount: 'usageCount',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CareerGuideScalarFieldEnum = {
  id: 'id',
  slug: 'slug',
  name: 'name',
  nameHi: 'nameHi',
  category: 'category',
  description: 'description',
  descriptionHi: 'descriptionHi',
  icon: 'icon',
  difficulty: 'difficulty',
  difficultyHi: 'difficultyHi',
  competition: 'competition',
  competitionHi: 'competitionHi',
  avgSalary: 'avgSalary',
  avgSalaryHi: 'avgSalaryHi',
  workType: 'workType',
  workTypeHi: 'workTypeHi',
  careerCategoryId: 'careerCategoryId',
  type: 'type',
  hidden: 'hidden',
  sortOrder: 'sortOrder',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CareerCategoryScalarFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  hidden: 'hidden',
  sortOrder: 'sortOrder',
  parentId: 'parentId',
  pathIds: 'pathIds',
  pathSlugs: 'pathSlugs',
  pathKey: 'pathKey',
  depth: 'depth',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CareerSectionScalarFieldEnum = {
  id: 'id',
  careerGuideId: 'careerGuideId',
  title: 'title',
  titleHi: 'titleHi',
  type: 'type',
  content: 'content',
  contentHi: 'contentHi',
  sortOrder: 'sortOrder',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ChapterAttemptScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  chapterId: 'chapterId',
  score: 'score',
  maxScore: 'maxScore',
  timeSpent: 'timeSpent',
  details: 'details',
  createdAt: 'createdAt'
};

exports.Prisma.MockCategoryScalarFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  icon: 'icon',
  sortOrder: 'sortOrder',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  isPaid: 'isPaid',
  price: 'price'
};

exports.Prisma.MockExamScalarFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  emoji: 'emoji',
  description: 'description',
  sortOrder: 'sortOrder',
  hidden: 'hidden',
  image: 'image',
  categoryId: 'categoryId',
  quizCategoryIds: 'quizCategoryIds',
  booksJson: 'booksJson',
  studyMaterialJson: 'studyMaterialJson',
  isPaid: 'isPaid',
  price: 'price',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.MockExamSectionScalarFieldEnum = {
  id: 'id',
  examId: 'examId',
  title: 'title',
  content: 'content',
  type: 'type',
  sortOrder: 'sortOrder',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.MockPaperScalarFieldEnum = {
  id: 'id',
  examId: 'examId',
  title: 'title',
  slug: 'slug',
  timeLimit: 'timeLimit',
  totalMarks: 'totalMarks',
  negativeMarking: 'negativeMarking',
  positiveMarking: 'positiveMarking',
  instructionType: 'instructionType',
  instructions: 'instructions',
  showSolutions: 'showSolutions',
  isLive: 'isLive',
  sortOrder: 'sortOrder',
  paperType: 'paperType',
  year: 'year',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.MockSectionScalarFieldEnum = {
  id: 'id',
  paperId: 'paperId',
  name: 'name',
  order: 'order',
  timeLimit: 'timeLimit',
  totalMarks: 'totalMarks',
  totalQuestions: 'totalQuestions',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.MockQuestionScalarFieldEnum = {
  id: 'id',
  paperId: 'paperId',
  sectionId: 'sectionId',
  text: 'text',
  textHi: 'textHi',
  options: 'options',
  optionsHi: 'optionsHi',
  answer: 'answer',
  explanation: 'explanation',
  explanationHi: 'explanationHi',
  image: 'image',
  type: 'type',
  difficulty: 'difficulty',
  sortOrder: 'sortOrder',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.MockAttemptScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  paperId: 'paperId',
  answersJson: 'answersJson',
  status: 'status',
  timeLeft: 'timeLeft',
  score: 'score',
  correctCount: 'correctCount',
  wrongCount: 'wrongCount',
  attemptedCount: 'attemptedCount',
  startedAt: 'startedAt',
  completedAt: 'completedAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.StudyMaterialScalarFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  image: 'image',
  description: 'description',
  authors: 'authors',
  alignedTo: 'alignedTo',
  publishDate: 'publishDate',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.StudySubjectScalarFieldEnum = {
  id: 'id',
  materialId: 'materialId',
  name: 'name',
  slug: 'slug',
  sortOrder: 'sortOrder',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.StudyChapterScalarFieldEnum = {
  id: 'id',
  subjectId: 'subjectId',
  title: 'title',
  slug: 'slug',
  content: 'content',
  videoId: 'videoId',
  sortOrder: 'sortOrder',
  practiceId: 'practiceId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.FunFactCategoryScalarFieldEnum = {
  id: 'id',
  name: 'name',
  nameHi: 'nameHi',
  slug: 'slug',
  image: 'image',
  sortOrder: 'sortOrder',
  hidden: 'hidden',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.FunFactScalarFieldEnum = {
  id: 'id',
  categoryId: 'categoryId',
  description: 'description',
  descriptionHi: 'descriptionHi',
  image: 'image',
  views: 'views',
  hidden: 'hidden',
  isDaily: 'isDaily',
  dailyDate: 'dailyDate',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.FunFactLikeScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  factId: 'factId',
  createdAt: 'createdAt'
};

exports.Prisma.FunFactFavoriteScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  factId: 'factId',
  createdAt: 'createdAt'
};

exports.Prisma.FunFactCommentScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  factId: 'factId',
  content: 'content',
  createdAt: 'createdAt'
};

exports.Prisma.TrueFalseCategoryScalarFieldEnum = {
  id: 'id',
  name: 'name',
  nameHi: 'nameHi',
  slug: 'slug',
  image: 'image',
  sortOrder: 'sortOrder',
  hidden: 'hidden',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.TrueFalseQuestionScalarFieldEnum = {
  id: 'id',
  categoryId: 'categoryId',
  statement: 'statement',
  statementHi: 'statementHi',
  correctAnswer: 'correctAnswer',
  explanation: 'explanation',
  explanationHi: 'explanationHi',
  image: 'image',
  views: 'views',
  hidden: 'hidden',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};


exports.Prisma.ModelName = {
  User: 'User',
  VerificationToken: 'VerificationToken',
  Account: 'Account',
  Category: 'Category',
  Question: 'Question',
  UserProgress: 'UserProgress',
  Favourite: 'Favourite',
  AdminAccount: 'AdminAccount',
  PendingTask: 'PendingTask',
  AdminActivityLog: 'AdminActivityLog',
  Setting: 'Setting',
  NavigationLink: 'NavigationLink',
  DailyQuiz: 'DailyQuiz',
  Section: 'Section',
  SubSection: 'SubSection',
  SchoolBoard: 'SchoolBoard',
  SchoolClass: 'SchoolClass',
  SchoolSubject: 'SchoolSubject',
  SchoolChapter: 'SchoolChapter',
  SchoolQuestion: 'SchoolQuestion',
  SchoolProgress: 'SchoolProgress',
  CurrentAffair: 'CurrentAffair',
  CoursePackage: 'CoursePackage',
  CourseOrder: 'CourseOrder',
  PromoCode: 'PromoCode',
  CareerGuide: 'CareerGuide',
  CareerCategory: 'CareerCategory',
  CareerSection: 'CareerSection',
  ChapterAttempt: 'ChapterAttempt',
  MockCategory: 'MockCategory',
  MockExam: 'MockExam',
  MockExamSection: 'MockExamSection',
  MockPaper: 'MockPaper',
  MockSection: 'MockSection',
  MockQuestion: 'MockQuestion',
  MockAttempt: 'MockAttempt',
  StudyMaterial: 'StudyMaterial',
  StudySubject: 'StudySubject',
  StudyChapter: 'StudyChapter',
  FunFactCategory: 'FunFactCategory',
  FunFact: 'FunFact',
  FunFactLike: 'FunFactLike',
  FunFactFavorite: 'FunFactFavorite',
  FunFactComment: 'FunFactComment',
  TrueFalseCategory: 'TrueFalseCategory',
  TrueFalseQuestion: 'TrueFalseQuestion'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
