require('dotenv').config({ path: '.env.local' });
require('dotenv').config();
const dns = require('dns');
dns.setServers(['8.8.8.8', '8.8.4.4']);
const { MongoClient, ObjectId } = require('mongodb');
const crypto = require('crypto');

function calculateQuestionHash({ text, options, correctIndex, category }) {
  const normText = (text || "").trim().toLowerCase().replace(/\s+/g, " ");
  const normOpts = (options || []).map((o) => (o || "").trim().toLowerCase()).sort().join("|");
  const raw = `${normText}:::${normOpts}:::${correctIndex}:::${category || ""}`;
  return crypto.createHash("sha1").update(raw).digest("hex");
}

const INDIA_CAT_ID = new ObjectId('69d03ea978a47c2438020859');
const WORLD_CAT_ID = new ObjectId('69d03eab78a47c2438020860');

const QUESTIONS = [
  // ── ANCIENT INDIAN HISTORY (India GK) ──
  {
    topicId: 'ancient-india-history',
    topicName: 'Ancient Indian History',
    category: 'India GK',
    categoryId: INDIA_CAT_ID,
    subTopic: 'Indus Valley Civilization',
    difficulty: 'easy',
    examTags: ['UPSC', 'SSC CGL', 'State PSC'],
    text: 'What was the ancient port city of the Indus Valley Civilization?',
    text_en: 'What was the ancient port city of the Indus Valley Civilization?',
    text_hi: 'सिंधु घाटी सभ्यता का प्राचीन बंदरगाह नगर कौन सा था?',
    options: ['Lothal', 'Harappa', 'Kalibangan', 'Mohenjo-daro'],
    options_en: ['Lothal', 'Harappa', 'Kalibangan', 'Mohenjo-daro'],
    options_hi: ['लोथल', 'हड़प्पा', 'कालीबंगन', 'मोहनजोदड़ो'],
    correctIndex: 0,
    explanation_en: 'Lothal in Gujarat was the major port and dockyard city of the Harappan civilization.',
    explanation_hi: 'गुजरात में लोथल हड़प्पा सभ्यता का प्रमुख बंदरगाह और गोदी (डॉकयार्ड) था।'
  },
  {
    topicId: 'ancient-india-history',
    topicName: 'Ancient Indian History',
    category: 'India GK',
    categoryId: INDIA_CAT_ID,
    subTopic: 'Vedic Period',
    difficulty: 'easy',
    examTags: ['SSC CGL', 'Railway RRB'],
    text: 'The Gayatri Mantra is contained in which of the four Vedas?',
    text_en: 'The Gayatri Mantra is contained in which of the four Vedas?',
    text_hi: 'गायत्री मंत्र चारों वेदों में से किसमें समाहित है?',
    options: ['Rigveda', 'Samaveda', 'Yajurveda', 'Atharvaveda'],
    options_en: ['Rigveda', 'Samaveda', 'Yajurveda', 'Atharvaveda'],
    options_hi: ['ऋग्वेद', 'सामवेद', 'यजुर्वेद', 'अथर्ववेद'],
    correctIndex: 0,
    explanation_en: 'The Gayatri Mantra is found in the 3rd Mandala of the Rigveda, composed by sage Vishvamitra.',
    explanation_hi: 'गायत्री मंत्र ऋग्वेद के तीसरे मंडल में मिलता है, जिसकी रचना ऋषि विश्वामित्र ने की थी।'
  },
  {
    topicId: 'ancient-india-history',
    topicName: 'Ancient Indian History',
    category: 'India GK',
    categoryId: INDIA_CAT_ID,
    subTopic: 'Mauryan Empire',
    difficulty: 'easy',
    examTags: ['UPSC', 'State PSC'],
    text: 'Who was the founder of the Maurya Empire?',
    text_en: 'Who was the founder of the Maurya Empire?',
    text_hi: 'मौर्य साम्राज्य का संस्थापक कौन था?',
    options: ['Chandragupta Maurya', 'Ashoka', 'Bindusara', 'Brihadratha'],
    options_en: ['Chandragupta Maurya', 'Ashoka', 'Bindusara', 'Brihadratha'],
    options_hi: ['चन्द्रगुप्त मौर्य', 'अशोक', 'बिन्दुसार', 'बृहद्रथ'],
    correctIndex: 0,
    explanation_en: 'Chandragupta Maurya founded the Maurya Empire with the guidance of Chanakya in 322 BCE.',
    explanation_hi: 'चन्द्रगुप्त मौर्य ने चाणक्य के मार्गदर्शन में 322 ईसा पूर्व में मौर्य साम्राज्य की स्थापना की थी।'
  },
  {
    topicId: 'ancient-india-history',
    topicName: 'Ancient Indian History',
    category: 'India GK',
    categoryId: INDIA_CAT_ID,
    subTopic: 'Mauryan Empire',
    difficulty: 'easy',
    examTags: ['SSC CGL', 'State PSC'],
    text: 'Which emperor embraced Buddhism after the Kalinga War?',
    text_en: 'Which emperor embraced Buddhism after the Kalinga War?',
    text_hi: 'कलिंग युद्ध के बाद किस सम्राट ने बौद्ध धर्म अपनाया था?',
    options: ['Emperor Ashoka', 'Chandragupta Maurya', 'Kanishka', 'Samudragupta'],
    options_en: ['Emperor Ashoka', 'Chandragupta Maurya', 'Kanishka', 'Samudragupta'],
    options_hi: ['सम्राट अशोक', 'चन्द्रगुप्त मौर्य', 'कनिष्क', 'समुद्रगुप्त'],
    correctIndex: 0,
    explanation_en: 'Emperor Ashoka adopted Buddhism after witnessing the devastation of the Kalinga War in 261 BCE.',
    explanation_hi: 'सम्राट अशोक ने 261 ईसा पूर्व में कलिंग युद्ध के विनाश को देखने के बाद बौद्ध धर्म अपना लिया था।'
  },
  {
    topicId: 'ancient-india-history',
    topicName: 'Ancient Indian History',
    category: 'India GK',
    categoryId: INDIA_CAT_ID,
    subTopic: 'Gupta Empire',
    difficulty: 'easy',
    examTags: ['UPSC', 'SSC CGL'],
    text: 'The famous Iron Pillar near Qutub Minar was built during which dynasty?',
    text_en: 'The famous Iron Pillar near Qutub Minar was built during which dynasty?',
    text_hi: 'कुतुब मीनार के पास प्रसिद्ध लौह स्तंभ किस राजवंश के समय बना था?',
    options: ['Gupta Dynasty', 'Maurya Dynasty', 'Kushan Dynasty', 'Chola Dynasty'],
    options_en: ['Gupta Dynasty', 'Maurya Dynasty', 'Kushan Dynasty', 'Chola Dynasty'],
    options_hi: ['गुप्त राजवंश', 'मौर्य राजवंश', 'कुषाण राजवंश', 'चोल राजवंश'],
    correctIndex: 0,
    explanation_en: 'The Iron Pillar of Delhi was erected by Chandragupta II (Vikramaditya) of the Gupta Empire.',
    explanation_hi: 'दिल्ली का लौह स्तंभ गुप्त साम्राज्य के चंद्रगुप्त द्वितीय (विक्रमादित्य) द्वारा बनवाया गया था।'
  },
  {
    topicId: 'ancient-india-history',
    topicName: 'Ancient Indian History',
    category: 'India GK',
    categoryId: INDIA_CAT_ID,
    subTopic: 'Gupta Empire',
    difficulty: 'easy',
    examTags: ['State PSC', 'Railway RRB'],
    text: 'Who was celebrated as the "Napoleon of India" by historian V.A. Smith?',
    text_en: 'Who was celebrated as the "Napoleon of India" by historian V.A. Smith?',
    text_hi: 'इतिहासकार वी.ए. स्मिथ ने किसे "भारत का नेपोलियन" कहा था?',
    options: ['Samudragupta', 'Chandragupta I', 'Skandagupta', 'Harshavardhana'],
    options_en: ['Samudragupta', 'Chandragupta I', 'Skandagupta', 'Harshavardhana'],
    options_hi: ['समुद्रगुप्त', 'चन्द्रगुप्त प्रथम', 'स्कन्दगुप्त', 'हर्षवर्धन'],
    correctIndex: 0,
    explanation_en: 'Samudragupta was dubbed the Napoleon of India due to his extensive military conquests across India.',
    explanation_hi: 'समुद्रगुप्त को उनके विस्तृत सैन्य अभियानों और विजयों के कारण भारत का नेपोलियन कहा गया।'
  },
  {
    topicId: 'ancient-india-history',
    topicName: 'Ancient Indian History',
    category: 'India GK',
    categoryId: INDIA_CAT_ID,
    subTopic: 'Art & Architecture',
    difficulty: 'easy',
    examTags: ['UPSC', 'State PSC'],
    text: 'The famous rock-cut Kailasa temple at Ellora was built by which dynasty?',
    text_en: 'The famous rock-cut Kailasa temple at Ellora was built by which dynasty?',
    text_hi: 'एलोरा का प्रसिद्ध शैलकृत कैलास मंदिर किस राजवंश द्वारा बनवाया गया था?',
    options: ['Rashtrakutas', 'Pallavas', 'Chalukyas', 'Cholas'],
    options_en: ['Rashtrakutas', 'Pallavas', 'Chalukyas', 'Cholas'],
    options_hi: ['राष्ट्रकूट', 'पल्लव', 'चालुक्य', 'चोल'],
    correctIndex: 0,
    explanation_en: 'Kailasa temple (Cave 16) at Ellora was commissioned by the Rashtrakuta king Krishna I in the 8th century.',
    explanation_hi: 'एलोरा का कैलास मंदिर (गुफा 16) 8वीं शताब्दी में राष्ट्रकूट राजा कृष्ण प्रथम द्वारा बनवाया गया था।'
  },
  {
    topicId: 'ancient-india-history',
    topicName: 'Ancient Indian History',
    category: 'India GK',
    categoryId: INDIA_CAT_ID,
    subTopic: 'Indus Valley Civilization',
    difficulty: 'medium',
    examTags: ['UPSC', 'SSC CGL'],
    text: 'In the Indus Valley Civilization, the "Great Bath" was discovered at which site?',
    text_en: 'In the Indus Valley Civilization, the "Great Bath" was discovered at which site?',
    text_hi: 'सिंधु घाटी सभ्यता में "विशाल स्नानागार" किस स्थल पर खोजा गया था?',
    options: ['Mohenjo-daro', 'Harappa', 'Dholavira', 'Banawali'],
    options_en: ['Mohenjo-daro', 'Harappa', 'Dholavira', 'Banawali'],
    options_hi: ['मोहनजोदड़ो', 'हड़प्पा', 'धोलावीरा', 'बनावली'],
    correctIndex: 0,
    explanation_en: 'The Great Bath was unearthed at Mohenjo-daro in Sindh (now Pakistan).',
    explanation_hi: 'विशाल स्नानागार सिंध (वर्तमान पाकिस्तान) में स्थित मोहनजोदड़ो में मिला था।'
  },
  {
    topicId: 'ancient-india-history',
    topicName: 'Ancient Indian History',
    category: 'India GK',
    categoryId: INDIA_CAT_ID,
    subTopic: 'Mauryan Empire',
    difficulty: 'medium',
    examTags: ['UPSC', 'State PSC'],
    text: 'Who wrote the Arthashastra, the ancient Indian treatise on statecraft and economic policy?',
    text_en: 'Who wrote the Arthashastra, the ancient Indian treatise on statecraft and economic policy?',
    text_hi: 'शासन कला और आर्थिक नीति पर प्राचीन भारतीय ग्रंथ अर्थशास्त्र किसने लिखा था?',
    options: ['Chanakya (Kautilya)', 'Banabhatta', 'Kalidasa', 'Varahamihira'],
    options_en: ['Chanakya (Kautilya)', 'Banabhatta', 'Kalidasa', 'Varahamihira'],
    options_hi: ['चाणक्य (कौटिल्य)', 'बाणभट्ट', 'कालिदास', 'वराहमिहिर'],
    correctIndex: 0,
    explanation_en: 'Kautilya (also known as Chanakya or Vishnugupta) authored the Arthashastra.',
    explanation_hi: 'कौटिल्य (चाणक्य या विष्णुगुप्त) ने अर्थशास्त्र की रचना की थी।'
  },
  {
    topicId: 'ancient-india-history',
    topicName: 'Ancient Indian History',
    category: 'India GK',
    categoryId: INDIA_CAT_ID,
    subTopic: 'Mauryan Empire',
    difficulty: 'medium',
    examTags: ['SSC CGL', 'UPSC'],
    text: 'Megasthenes, the author of Indica, visited India during the reign of which ruler?',
    text_en: 'Megasthenes, the author of Indica, visited India during the reign of which ruler?',
    text_hi: 'इंडिका के लेखक मेगस्थनीज किस शासक के शासनकाल में भारत आए थे?',
    options: ['Chandragupta Maurya', 'Ashoka', 'Harshavardhana', 'Kanishka'],
    options_en: ['Chandragupta Maurya', 'Ashoka', 'Harshavardhana', 'Kanishka'],
    options_hi: ['चन्द्रगुप्त मौर्य', 'अशोक', 'हर्षवर्धन', 'कनिष्क'],
    correctIndex: 0,
    explanation_en: 'Megasthenes was an ambassador of Seleucus I Nicator sent to the court of Chandragupta Maurya.',
    explanation_hi: 'मेगस्थनीज सेल्यूकस प्रथम निकेटर का राजदूत था जिसे चन्द्रगुप्त मौर्य के दरबार में भेजा गया था।'
  },
  {
    topicId: 'ancient-india-history',
    topicName: 'Ancient Indian History',
    category: 'India GK',
    categoryId: INDIA_CAT_ID,
    subTopic: 'Buddhism & Jainism',
    difficulty: 'medium',
    examTags: ['UPSC', 'State PSC'],
    text: 'The Fourth Buddhist Council in Kundalvana (Kashmir) was convened during the reign of which king?',
    text_en: 'The Fourth Buddhist Council in Kundalvana (Kashmir) was convened during the reign of which king?',
    text_hi: 'कुंडलवन (कश्मीर) में चतुर्थ बौद्ध संगीति किस राजा के शासनकाल में आयोजित हुई थी?',
    options: ['Kanishka', 'Ashoka', 'Kalashoka', 'Ajatashatru'],
    options_en: ['Kanishka', 'Ashoka', 'Kalashoka', 'Ajatashatru'],
    options_hi: ['कनिष्क', 'अशोक', 'कालाशोक', 'अजातशत्रु'],
    correctIndex: 0,
    explanation_en: 'The 4th Buddhist Council was held under the patronage of Kushan King Kanishka in Kashmir.',
    explanation_hi: 'चतुर्थ बौद्ध संगीति कुषाण शासक कनिष्क के संरक्षण में कश्मीर में आयोजित की गई थी।'
  },
  {
    topicId: 'ancient-india-history',
    topicName: 'Ancient Indian History',
    category: 'India GK',
    categoryId: INDIA_CAT_ID,
    subTopic: 'Gupta Empire',
    difficulty: 'medium',
    examTags: ['State PSC', 'SSC CGL'],
    text: 'Nalanda Mahavihara was founded during the 5th century by which Gupta emperor?',
    text_en: 'Nalanda Mahavihara was founded during the 5th century by which Gupta emperor?',
    text_hi: '5वीं शताब्दी में नालंदा महाविहार की स्थापना किस गुप्त सम्राट ने की थी?',
    options: ['Kumaragupta I', 'Chandragupta II', 'Samudragupta', 'Buddhagupta'],
    options_en: ['Kumaragupta I', 'Chandragupta II', 'Samudragupta', 'Buddhagupta'],
    options_hi: ['कुमारगुप्त प्रथम', 'चन्द्रगुप्त द्वितीय', 'समुद्रगुप्त', 'बुद्धगुप्त'],
    correctIndex: 0,
    explanation_en: 'Kumaragupta I (Shakraditya) established the ancient university of Nalanda.',
    explanation_hi: 'कुमारगुप्त प्रथम (शक्रादित्य) ने प्राचीन नालंदा विश्वविद्यालय की स्थापना की थी।'
  },
  {
    topicId: 'ancient-india-history',
    topicName: 'Ancient Indian History',
    category: 'India GK',
    categoryId: INDIA_CAT_ID,
    subTopic: 'Post-Gupta Period',
    difficulty: 'medium',
    examTags: ['SSC CGL', 'State PSC'],
    text: 'Who was the celebrated court poet of King Harshavardhana who authored Harshacharita?',
    text_en: 'Who was the celebrated court poet of King Harshavardhana who authored Harshacharita?',
    text_hi: 'राजा हर्षवर्धन के प्रसिद्ध दरबारी कवि कौन थे जिन्होंने हर्षचरित की रचना की?',
    options: ['Banabhatta', 'Dandin', 'Bhavabhuti', 'Harishena'],
    options_en: ['Banabhatta', 'Dandin', 'Bhavabhuti', 'Harishena'],
    options_hi: ['बाणभट्ट', 'दण्डी', 'भवभूति', 'हरिषेण'],
    correctIndex: 0,
    explanation_en: 'Banabhatta was Harsha’s Asthana Kavi and wrote Harshacharita and Kadambari.',
    explanation_hi: 'बाणभट्ट हर्षवर्धन के दरबारी कवि थे जिन्होंने हर्षचरित और कादंबरी लिखी थी।'
  },
  {
    topicId: 'ancient-india-history',
    topicName: 'Ancient Indian History',
    category: 'India GK',
    categoryId: INDIA_CAT_ID,
    subTopic: 'South Indian Dynasties',
    difficulty: 'medium',
    examTags: ['UPSC', 'State PSC'],
    text: 'In ancient South India, what did the term "Manigramam" refer to?',
    text_en: 'In ancient South India, what did the term "Manigramam" refer to?',
    text_hi: 'प्राचीन दक्षिण भारत में "मणिग्रामम" शब्द का क्या तात्पर्य था?',
    options: ['A Guild of Merchants', 'An Assembly of Priests', 'A Revenue District', 'A Military Garrison'],
    options_en: ['A Guild of Merchants', 'An Assembly of Priests', 'A Revenue District', 'A Military Garrison'],
    options_hi: ['व्यापारियों का संघ (गिल्ड)', 'पुजारियों की सभा', 'एक राजस्व जिला', 'एक सैन्य छावनी'],
    correctIndex: 0,
    explanation_en: 'Manigramam was a prominent merchant guild operating in South India and Southeast Asia.',
    explanation_hi: 'मणिग्रामम दक्षिण भारत और दक्षिण-पूर्व एशिया में सक्रिय व्यापारियों का एक प्रमुख संघ था।'
  },
  {
    topicId: 'ancient-india-history',
    topicName: 'Ancient Indian History',
    category: 'India GK',
    categoryId: INDIA_CAT_ID,
    subTopic: 'Vedic Period',
    difficulty: 'hard',
    examTags: ['UPSC', 'State PSC'],
    text: 'The 14th century BCE Boghazkoi inscription in Asia Minor explicitly invokes which four Rigvedic deities?',
    text_en: 'The 14th century BCE Boghazkoi inscription in Asia Minor explicitly invokes which four Rigvedic deities?',
    text_hi: 'एशिया माइनर में 14वीं शताब्दी ईसा पूर्व के बोगजकोई शिलालेख में किन चार ऋग्वैदिक देवताओं का उल्लेख है?',
    options: ['Indra, Varuna, Mitra, Nasatya', 'Agni, Soma, Surya, Vayu', 'Brahma, Vishnu, Mahesh, Indra', 'Yama, Kubera, Varuna, Surya'],
    options_en: ['Indra, Varuna, Mitra, Nasatya', 'Agni, Soma, Surya, Vayu', 'Brahma, Vishnu, Mahesh, Indra', 'Yama, Kubera, Varuna, Surya'],
    options_hi: ['इन्द्र, वरुण, मित्र, नासत्य', 'अग्नि, सोम, सूर्य, वायु', 'ब्रह्मा, विष्णु, महेश, इन्द्र', 'यम, कुबेर, वरुण, सूर्य'],
    correctIndex: 0,
    explanation_en: 'The treaty between the Hittites and Mitanni at Boghazkoi invokes Indra, Varuna, Mitra, and the Nasatyas.',
    explanation_hi: 'बोगजकोई में हित्ती और मितान्नी संधि में इन्द्र, वरुण, मित्र और नासत्य देवताओं का आह्वान किया गया है।'
  },
  {
    topicId: 'ancient-india-history',
    topicName: 'Ancient Indian History',
    category: 'India GK',
    categoryId: INDIA_CAT_ID,
    subTopic: 'Mauryan Empire',
    difficulty: 'hard',
    examTags: ['UPSC', 'State PSC'],
    text: 'Which Major Rock Edict of Ashoka provides the definitive historical account of the Kalinga War?',
    text_en: 'Which Major Rock Edict of Ashoka provides the definitive historical account of the Kalinga War?',
    text_hi: 'अशोक का कौन सा प्रमुख शिलालेख कलिंग युद्ध का प्रामाणिक ऐतिहासिक विवरण देता है?',
    options: ['Major Rock Edict XIII', 'Major Rock Edict X', 'Major Rock Edict V', 'Major Rock Edict I'],
    options_en: ['Major Rock Edict XIII', 'Major Rock Edict X', 'Major Rock Edict V', 'Major Rock Edict I'],
    options_hi: ['13वां प्रमुख शिलालेख (XIII)', '10वां प्रमुख शिलालेख (X)', '5वां प्रमुख शिलालेख (V)', 'पहला प्रमुख शिलालेख (I)'],
    correctIndex: 0,
    explanation_en: 'Major Rock Edict XIII vividly describes the destruction of Kalinga and Ashoka’s remorse and conversion.',
    explanation_hi: '13वां प्रमुख शिलालेख कलिंग के विनाश, अशोक के पश्चाताप और धम्म विजय का सजीव वर्णन करता है।'
  },
  {
    topicId: 'ancient-india-history',
    topicName: 'Ancient Indian History',
    category: 'India GK',
    categoryId: INDIA_CAT_ID,
    subTopic: 'Mauryan Empire',
    difficulty: 'hard',
    examTags: ['UPSC'],
    text: 'According to Kautilya’s Saptanga Theory of State, which element is described as the "Eyes" of the state?',
    text_en: 'According to Kautilya’s Saptanga Theory of State, which element is described as the "Eyes" of the state?',
    text_hi: 'कौटिल्य के सप्तांग सिद्धांत के अनुसार राज्य के "नेत्र" के रूप में किस अंग का वर्णन किया गया है?',
    options: ['Amatya (Ministers/Bureaucrats)', 'Svamin (King)', 'Kosha (Treasury)', 'Durga (Fort)'],
    options_en: ['Amatya (Ministers/Bureaucrats)', 'Svamin (King)', 'Kosha (Treasury)', 'Durga (Fort)'],
    options_hi: ['अमात्य (मंत्री/अधिकारी)', 'स्वामी (राजा)', 'कोष (खजाना)', 'दुर्ग (किला)'],
    correctIndex: 0,
    explanation_en: 'In Saptanga theory, Svamin is the head, Amatya are the eyes, Janapada are the legs, and Kosha is the mouth.',
    explanation_hi: 'सप्तांग सिद्धांत में राजा सिर, अमात्य आंखें, जनपद पैर और कोष मुख के समान माने गए हैं।'
  },
  {
    topicId: 'ancient-india-history',
    topicName: 'Ancient Indian History',
    category: 'India GK',
    categoryId: INDIA_CAT_ID,
    subTopic: 'Post-Mauryan Period',
    difficulty: 'expert',
    examTags: ['UPSC CSE'],
    text: 'The 2nd century BCE Heliodorus Pillar discovered at Besnagar (Vidisha) was dedicated to which deity?',
    text_en: 'The 2nd century BCE Heliodorus Pillar discovered at Besnagar (Vidisha) was dedicated to which deity?',
    text_hi: 'विदिशा के बेसनगर में प्राप्त दूसरी शताब्दी ईसा पूर्व का हेलियोडोरस स्तंभ किस देवता को समर्पित था?',
    options: ['Vasudeva (Vishnu)', 'Shiva (Mahadeva)', 'Gautama Buddha', 'Kartikeya'],
    options_en: ['Vasudeva (Vishnu)', 'Shiva (Mahadeva)', 'Gautama Buddha', 'Kartikeya'],
    options_hi: ['वासुदेव (विष्णु)', 'शिव (महादेव)', 'गौतम बुद्ध', 'कार्तिकेय'],
    correctIndex: 0,
    explanation_en: 'Heliodorus, an Indo-Greek ambassador from Taxila, declared himself a Bhagavata and erected the Garuda pillar for Vasudeva.',
    explanation_hi: 'तक्षशिला के इंडो-ग्रीक राजदूत हेलियोडोरस ने स्वयं को भागवत घोषित कर वासुदेव के लिए गरुड़ स्तंभ स्थापित किया था।'
  },
  {
    topicId: 'ancient-india-history',
    topicName: 'Ancient Indian History',
    category: 'India GK',
    categoryId: INDIA_CAT_ID,
    subTopic: 'Chalukyas & Harshavardhana',
    difficulty: 'expert',
    examTags: ['UPSC CSE'],
    text: 'The famous Aihole Inscription detailing Pulakeshin II’s victory over Harsha on the Narmada was composed by whom?',
    text_en: 'The famous Aihole Inscription detailing Pulakeshin II’s victory over Harsha on the Narmada was composed by whom?',
    text_hi: 'नर्मदा तट पर हर्ष पर पुलकेशिन द्वितीय की विजय का वर्णन करने वाला प्रसिद्ध ऐहोल प्रशस्ति अभिलेख किसने रचा था?',
    options: ['Ravikirti', 'Harishena', 'Virsen', 'Bilhana'],
    options_en: ['Ravikirti', 'Harishena', 'Virsen', 'Bilhana'],
    options_hi: ['रविकीर्ति', 'हरिषेण', 'वीरसेन', 'बिल्हण'],
    correctIndex: 0,
    explanation_en: 'The Aihole prashasti was composed in chaste Sanskrit by the Jain poet Ravikirti, court poet of Pulakeshin II.',
    explanation_hi: 'ऐहोल प्रशस्ति की रचना पुलकेशिन द्वितीय के दरबारी कवि जैन विद्वान रविकीर्ति ने संस्कृत में की थी।'
  },
  {
    topicId: 'ancient-india-history',
    topicName: 'Ancient Indian History',
    category: 'India GK',
    categoryId: INDIA_CAT_ID,
    subTopic: 'Western Kshatrapas',
    difficulty: 'expert',
    examTags: ['UPSC CSE'],
    text: 'The Junagadh rock inscription of Shaka ruler Rudradaman I is celebrated in epigraphy primarily because it is:',
    text_en: 'The Junagadh rock inscription of Shaka ruler Rudradaman I is celebrated in epigraphy primarily because it is:',
    text_hi: 'शक शासक रुद्रदामन प्रथम का जूनागढ़ शिलालेख पुरालेखशास्त्र में मुख्य रूप से क्यों प्रसिद्ध है?',
    options: [
      'The earliest long inscription in pure classical Sanskrit prose',
      'The first inscription mentioning the zero digit',
      'The earliest bilingual Tamil-Brahmi rock edict',
      'The only inscription recording a naval battle in the Arabian Sea'
    ],
    options_en: [
      'The earliest long inscription in pure classical Sanskrit prose',
      'The first inscription mentioning the zero digit',
      'The earliest bilingual Tamil-Brahmi rock edict',
      'The only inscription recording a naval battle in the Arabian Sea'
    ],
    options_hi: [
      'विशुद्ध शास्त्रीय संस्कृत गद्य में लिखा पहला लंबा शिलालेख',
      'शून्य अंक का उल्लेख करने वाला पहला शिलालेख',
      'सबसे पहला द्विभाषी तमिल-ब्राह्मी शिलालेख',
      'अरब सागर में नौसैनिक युद्ध का एकमात्र दर्ज अभिलेख'
    ],
    correctIndex: 0,
    explanation_en: 'The Junagadh inscription (c. 150 CE) is the earliest known substantial Sanskrit prose inscription, recording repairs to the Sudarshana Lake.',
    explanation_hi: 'जूनागढ़ शिलालेख (लगभग 150 ईस्वी) सुदर्शन झील के जीर्णोद्धार का वर्णन करने वाला शुद्ध संस्कृत गद्य का सबसे प्राचीन लंबा अभिलेख है।'
  },

  // ── INDIAN POLITY & CONSTITUTION (India GK) ──
  {
    topicId: 'indian-polity-constitution',
    topicName: 'Indian Polity & Constitution',
    category: 'India GK',
    categoryId: INDIA_CAT_ID,
    subTopic: 'Constitutional Framework',
    difficulty: 'easy',
    examTags: ['UPSC', 'SSC CGL', 'State PSC'],
    text: 'Who is revered as the Father of the Indian Constitution and chaired the Drafting Committee?',
    text_en: 'Who is revered as the Father of the Indian Constitution and chaired the Drafting Committee?',
    text_hi: 'भारतीय संविधान के जनक और प्रारूप समिति के अध्यक्ष कौन थे?',
    options: ['Dr. B.R. Ambedkar', 'Dr. Rajendra Prasad', 'Jawaharlal Nehru', 'Sardar Vallabhbhai Patel'],
    options_en: ['Dr. B.R. Ambedkar', 'Dr. Rajendra Prasad', 'Jawaharlal Nehru', 'Sardar Vallabhbhai Patel'],
    options_hi: ['डॉ. बी.आर. अम्बेडकर', 'डॉ. राजेन्द्र प्रसाद', 'जवाहरलाल नेहरू', 'सरदार वल्लभभाई पटेल'],
    correctIndex: 0,
    explanation_en: 'Dr. B.R. Ambedkar chaired the Drafting Committee of the Constituent Assembly.',
    explanation_hi: 'डॉ. बी.आर. अम्बेडकर संविधान सभा की प्रारूप समिति के अध्यक्ष थे।'
  },
  {
    topicId: 'indian-polity-constitution',
    topicName: 'Indian Polity & Constitution',
    category: 'India GK',
    categoryId: INDIA_CAT_ID,
    subTopic: 'Union Executive',
    difficulty: 'easy',
    examTags: ['SSC CGL', 'Railway RRB'],
    text: 'What is the minimum age prescribed by the Constitution to be eligible for election as President of India?',
    text_en: 'What is the minimum age prescribed by the Constitution to be eligible for election as President of India?',
    text_hi: 'भारत के राष्ट्रपति चुनाव के लिए संविधान द्वारा निर्धारित न्यूनतम आयु क्या है?',
    options: ['35 years', '30 years', '25 years', '21 years'],
    options_en: ['35 years', '30 years', '25 years', '21 years'],
    options_hi: ['35 वर्ष', '30 वर्ष', '25 वर्ष', '21 वर्ष'],
    correctIndex: 0,
    explanation_en: 'Article 58 prescribes that a candidate for President of India must be at least 35 years of age.',
    explanation_hi: 'अनुच्छेद 58 के अनुसार भारत के राष्ट्रपति पद के उम्मीदवार की आयु कम से कम 35 वर्ष होनी चाहिए।'
  },
  {
    topicId: 'indian-polity-constitution',
    topicName: 'Indian Polity & Constitution',
    category: 'India GK',
    categoryId: INDIA_CAT_ID,
    subTopic: 'Fundamental Rights',
    difficulty: 'easy',
    examTags: ['UPSC', 'State PSC'],
    text: 'Which Article of the Constitution guarantees equality before law and equal protection of the laws?',
    text_en: 'Which Article of the Constitution guarantees equality before law and equal protection of the laws?',
    text_hi: 'संविधान का कौन सा अनुच्छेद विधि के समक्ष समता और विधियों के समान संरक्षण की गारंटी देता है?',
    options: ['Article 14', 'Article 19', 'Article 21', 'Article 32'],
    options_en: ['Article 14', 'Article 19', 'Article 21', 'Article 32'],
    options_hi: ['अनुच्छेद 14', 'अनुच्छेद 19', 'अनुच्छेद 21', 'अनुच्छेद 32'],
    correctIndex: 0,
    explanation_en: 'Article 14 guarantees that the State shall not deny to any person equality before the law within India.',
    explanation_hi: 'अनुच्छेद 14 भारत के राज्यक्षेत्र में किसी व्यक्ति को विधि के समक्ष समता से वंचित नहीं करने की गारंटी देता है।'
  },
  {
    topicId: 'indian-polity-constitution',
    topicName: 'Indian Polity & Constitution',
    category: 'India GK',
    categoryId: INDIA_CAT_ID,
    subTopic: 'Fundamental Rights',
    difficulty: 'easy',
    examTags: ['SSC CGL', 'Railway RRB'],
    text: 'How many Fundamental Rights are currently recognized by the Constitution of India?',
    text_en: 'How many Fundamental Rights are currently recognized by the Constitution of India?',
    text_hi: 'वर्तमान में भारतीय संविधान द्वारा कितने मौलिक अधिकारों को मान्यता दी गई है?',
    options: ['6', '7', '8', '10'],
    options_en: ['6', '7', '8', '10'],
    options_hi: ['6', '7', '8', '10'],
    correctIndex: 0,
    explanation_en: 'Originally there were 7 rights; the Right to Property was removed in 1978, leaving 6 Fundamental Rights.',
    explanation_hi: 'मूल रूप से 7 अधिकार थे; 1978 में संपत्ति का अधिकार हटाए जाने के बाद 6 मौलिक अधिकार शेष हैं।'
  },
  {
    topicId: 'indian-polity-constitution',
    topicName: 'Indian Polity & Constitution',
    category: 'India GK',
    categoryId: INDIA_CAT_ID,
    subTopic: 'State Executive',
    difficulty: 'easy',
    examTags: ['State PSC', 'SSC CGL'],
    text: 'Who acts as the Constitutional Head of a State in India?',
    text_en: 'Who acts as the Constitutional Head of a State in India?',
    text_hi: 'भारत में किसी राज्य का संवैधानिक प्रमुख कौन होता है?',
    options: ['Governor', 'Chief Minister', 'Chief Justice of High Court', 'Speaker of Legislative Assembly'],
    options_en: ['Governor', 'Chief Minister', 'Chief Justice of High Court', 'Speaker of Legislative Assembly'],
    options_hi: ['राज्यपाल', 'मुख्यमंत्री', 'उच्च न्यायालय के मुख्य न्यायाधीश', 'विधानसभा अध्यक्ष'],
    correctIndex: 0,
    explanation_en: 'The Governor is the constitutional and executive head of the state under Article 154.',
    explanation_hi: 'अनुच्छेद 154 के तहत राज्यपाल राज्य का संवैधानिक और कार्यपालिका प्रमुख होता है।'
  },
  {
    topicId: 'indian-polity-constitution',
    topicName: 'Indian Polity & Constitution',
    category: 'India GK',
    categoryId: INDIA_CAT_ID,
    subTopic: 'Parliament of India',
    difficulty: 'easy',
    examTags: ['UPSC', 'SSC CGL'],
    text: 'Who is the ex-officio Chairman of the Council of States (Rajya Sabha)?',
    text_en: 'Who is the ex-officio Chairman of the Council of States (Rajya Sabha)?',
    text_hi: 'राज्य सभा के पदेन सभापति कौन होते हैं?',
    options: ['Vice-President of India', 'President of India', 'Prime Minister', 'Chief Justice of India'],
    options_en: ['Vice-President of India', 'President of India', 'Prime Minister', 'Chief Justice of India'],
    options_hi: ['भारत के उपराष्ट्रपति', 'भारत के राष्ट्रपति', 'प्रधानमंत्री', 'भारत के मुख्य न्यायाधीश'],
    correctIndex: 0,
    explanation_en: 'Under Article 64, the Vice-President of India is the ex-officio Chairman of the Rajya Sabha.',
    explanation_hi: 'अनुच्छेद 64 के अनुसार, भारत के उपराष्ट्रपति राज्य सभा के पदेन सभापति होते हैं।'
  },
  {
    topicId: 'indian-polity-constitution',
    topicName: 'Indian Polity & Constitution',
    category: 'India GK',
    categoryId: INDIA_CAT_ID,
    subTopic: 'Schedules of Constitution',
    difficulty: 'easy',
    examTags: ['State PSC', 'Railway RRB'],
    text: 'Which Schedule of the Indian Constitution allocates seats in the Rajya Sabha to States and UTs?',
    text_en: 'Which Schedule of the Indian Constitution allocates seats in the Rajya Sabha to States and UTs?',
    text_hi: 'भारतीय संविधान की कौन सी अनुसूची राज्यों और केंद्र शासित प्रदेशों को राज्य सभा में सीटों का आवंटन करती है?',
    options: ['Fourth Schedule', 'Second Schedule', 'Seventh Schedule', 'Tenth Schedule'],
    options_en: ['Fourth Schedule', 'Second Schedule', 'Seventh Schedule', 'Tenth Schedule'],
    options_hi: ['चौथी अनुसूची', 'दूसरी अनुसूची', 'सातवीं अनुसूची', 'दसवीं अनुसूची'],
    correctIndex: 0,
    explanation_en: 'The Fourth Schedule contains provisions as to the allocation of seats in the Council of States.',
    explanation_hi: 'चौथी अनुसूची में राज्य सभा में सीटों के आवंटन का प्रावधान है।'
  },
  {
    topicId: 'indian-polity-constitution',
    topicName: 'Indian Polity & Constitution',
    category: 'India GK',
    categoryId: INDIA_CAT_ID,
    subTopic: 'Constitutional Amendments',
    difficulty: 'medium',
    examTags: ['UPSC', 'SSC CGL'],
    text: 'Which Constitutional Amendment Act reduced the voting age in India from 21 years to 18 years?',
    text_en: 'Which Constitutional Amendment Act reduced the voting age in India from 21 years to 18 years?',
    text_hi: 'किस संविधान संशोधन अधिनियम ने भारत में मतदान की आयु 21 वर्ष से घटाकर 18 वर्ष कर दी?',
    options: ['61st Amendment Act, 1988', '42nd Amendment Act, 1976', '44th Amendment Act, 1978', '73rd Amendment Act, 1992'],
    options_en: ['61st Amendment Act, 1988', '42nd Amendment Act, 1976', '44th Amendment Act, 1978', '73rd Amendment Act, 1992'],
    options_hi: ['61वां संशोधन अधिनियम, 1988', '42वां संशोधन अधिनियम, 1976', '44वां संशोधन अधिनियम, 1978', '73वां संशोधन अधिनियम, 1992'],
    correctIndex: 0,
    explanation_en: 'The 61st Constitutional Amendment Act, 1988 amended Article 326 to lower the voting age to 18.',
    explanation_hi: '61वें संविधान संशोधन अधिनियम (1988) ने अनुच्छेद 326 में संशोधन कर मतदान की आयु 18 वर्ष की।'
  },
  {
    topicId: 'indian-polity-constitution',
    topicName: 'Indian Polity & Constitution',
    category: 'India GK',
    categoryId: INDIA_CAT_ID,
    subTopic: 'Preamble',
    difficulty: 'medium',
    examTags: ['UPSC', 'State PSC'],
    text: 'The words "Socialist", "Secular", and "Integrity" were incorporated into the Preamble by which Amendment?',
    text_en: 'The words "Socialist", "Secular", and "Integrity" were incorporated into the Preamble by which Amendment?',
    text_hi: 'प्रस्तावना में "समाजवादी", "पंथनिरपेक्ष" और "अखंडता" शब्द किस संशोधन द्वारा जोड़े गए थे?',
    options: ['42nd Amendment Act, 1976', '44th Amendment Act, 1978', '52nd Amendment Act, 1985', '86th Amendment Act, 2002'],
    options_en: ['42nd Amendment Act, 1976', '44th Amendment Act, 1978', '52nd Amendment Act, 1985', '86th Amendment Act, 2002'],
    options_hi: ['42वां संशोधन अधिनियम, 1976', '44वां संशोधन अधिनियम, 1978', '52वां संशोधन अधिनियम, 1985', '86वां संशोधन अधिनियम, 2002'],
    correctIndex: 0,
    explanation_en: 'The 42nd Amendment Act, 1976 added the terms Socialist, Secular, and Integrity to the Preamble.',
    explanation_hi: '42वें संशोधन अधिनियम, 1976 ने प्रस्तावना में समाजवादी, पंथनिरपेक्ष और अखंडता शब्द जोड़े।'
  },
  {
    topicId: 'indian-polity-constitution',
    topicName: 'Indian Polity & Constitution',
    category: 'India GK',
    categoryId: INDIA_CAT_ID,
    subTopic: 'Writ Jurisdiction',
    difficulty: 'medium',
    examTags: ['UPSC', 'SSC CGL'],
    text: 'Which prerogative writ is issued by courts to secure the release of an unlawfully detained person?',
    text_en: 'Which prerogative writ is issued by courts to secure the release of an unlawfully detained person?',
    text_hi: 'गैरकानूनी रूप से हिरासत में लिए गए व्यक्ति की रिहाई सुनिश्चित करने के लिए न्यायालय कौन सी रिट जारी करता है?',
    options: ['Habeas Corpus', 'Mandamus', 'Certiorari', 'Quo-Warranto'],
    options_en: ['Habeas Corpus', 'Mandamus', 'Certiorari', 'Quo-Warranto'],
    options_hi: ['बन्दी प्रत्यक्षीकरण (Habeas Corpus)', 'परमादेश (Mandamus)', 'उत्प्रेषण (Certiorari)', 'अधिकार पृच्छा (Quo-Warranto)'],
    correctIndex: 0,
    explanation_en: 'Habeas Corpus literally means "to have the body" and protects individual personal liberty against arbitrary arrest.',
    explanation_hi: 'बंदी प्रत्यक्षीकरण का शाब्दिक अर्थ है "सशरीर प्रस्तुत करना", जो अवैध हिरासत के विरुद्ध व्यक्तिगत स्वतंत्रता की रक्षा करता है।'
  },
  {
    topicId: 'indian-polity-constitution',
    topicName: 'Indian Polity & Constitution',
    category: 'India GK',
    categoryId: INDIA_CAT_ID,
    subTopic: 'Constitutional Remedies',
    difficulty: 'medium',
    examTags: ['UPSC', 'State PSC'],
    text: 'Which Article was termed the "Heart and Soul" of the Indian Constitution by Dr. B.R. Ambedkar?',
    text_en: 'Which Article was termed the "Heart and Soul" of the Indian Constitution by Dr. B.R. Ambedkar?',
    text_hi: 'डॉ. बी.आर. अम्बेडकर ने किस अनुच्छेद को भारतीय संविधान का "हृदय और आत्मा" कहा था?',
    options: ['Article 32', 'Article 21', 'Article 19', 'Article 368'],
    options_en: ['Article 32', 'Article 21', 'Article 19', 'Article 368'],
    options_hi: ['अनुच्छेद 32', 'अनुच्छेद 21', 'अनुच्छेद 19', 'अनुच्छेद 368'],
    correctIndex: 0,
    explanation_en: 'Article 32 provides the Right to Constitutional Remedies, without which other fundamental rights would be ineffective.',
    explanation_hi: 'अनुच्छेद 32 संवैधानिक उपचारों का अधिकार प्रदान करता है, जिसके बिना अन्य मौलिक अधिकार निष्प्रभावी हो जाते।'
  },
  {
    topicId: 'indian-polity-constitution',
    topicName: 'Indian Polity & Constitution',
    category: 'India GK',
    categoryId: INDIA_CAT_ID,
    subTopic: 'Emergency Provisions',
    difficulty: 'medium',
    examTags: ['SSC CGL', 'State PSC'],
    text: 'Under which Article of the Constitution can the President proclaim a Financial Emergency?',
    text_en: 'Under which Article of the Constitution can the President proclaim a Financial Emergency?',
    text_hi: 'संविधान के किस अनुच्छेद के तहत राष्ट्रपति वित्तीय आपातकाल की घोषणा कर सकते हैं?',
    options: ['Article 360', 'Article 352', 'Article 356', 'Article 365'],
    options_en: ['Article 360', 'Article 352', 'Article 356', 'Article 365'],
    options_hi: ['अनुच्छेद 360', 'अनुच्छेद 352', 'अनुच्छेद 356', 'अनुच्छेद 365'],
    correctIndex: 0,
    explanation_en: 'Article 360 empowers the President to proclaim Financial Emergency if financial stability of India is threatened.',
    explanation_hi: 'अनुच्छेद 360 राष्ट्रपति को भारत की वित्तीय स्थिरता खतरे में होने पर वित्तीय आपातकाल लगाने की शक्ति देता है।'
  },
  {
    topicId: 'indian-polity-constitution',
    topicName: 'Indian Polity & Constitution',
    category: 'India GK',
    categoryId: INDIA_CAT_ID,
    subTopic: 'Parliamentary Procedures',
    difficulty: 'medium',
    examTags: ['UPSC', 'State PSC'],
    text: 'How many distinguished members can the President of India nominate to the Rajya Sabha?',
    text_en: 'How many distinguished members can the President of India nominate to the Rajya Sabha?',
    text_hi: 'भारत के राष्ट्रपति राज्य सभा में कितने प्रतिष्ठित सदस्यों को मनोनीत कर सकते हैं?',
    options: ['12', '2', '10', '14'],
    options_en: ['12', '2', '10', '14'],
    options_hi: ['12', '2', '10', '14'],
    correctIndex: 0,
    explanation_en: 'Under Article 80, the President nominates 12 members having special knowledge in literature, science, art, and social service.',
    explanation_hi: 'अनुच्छेद 80 के तहत राष्ट्रपति साहित्य, विज्ञान, कला और समाज सेवा में विशेष ज्ञान रखने वाले 12 सदस्यों को मनोनीत करते हैं।'
  },
  {
    topicId: 'indian-polity-constitution',
    topicName: 'Indian Polity & Constitution',
    category: 'India GK',
    categoryId: INDIA_CAT_ID,
    subTopic: 'Anti-Defection Law',
    difficulty: 'medium',
    examTags: ['SSC CGL', 'UPSC'],
    text: 'The Anti-Defection Law was introduced via the 52nd Amendment in which Schedule of the Constitution?',
    text_en: 'The Anti-Defection Law was introduced via the 52nd Amendment in which Schedule of the Constitution?',
    text_hi: 'दलबदल विरोधी कानून 52वें संशोधन द्वारा संविधान की किस अनुसूची में शामिल किया गया था?',
    options: ['Tenth Schedule', 'Ninth Schedule', 'Eleventh Schedule', 'Twelfth Schedule'],
    options_en: ['Tenth Schedule', 'Ninth Schedule', 'Eleventh Schedule', 'Twelfth Schedule'],
    options_hi: ['दसवीं अनुसूची', 'नौवीं अनुसूची', 'ग्यारहवीं अनुसूची', 'बारहवीं अनुसूची'],
    correctIndex: 0,
    explanation_en: 'The 10th Schedule was added in 1985 to curb political defections.',
    explanation_hi: 'दसवीं अनुसूची को 1985 में राजनीतिक दलबदल पर रोक लगाने के लिए जोड़ा गया था।'
  },
  {
    topicId: 'indian-polity-constitution',
    topicName: 'Indian Polity & Constitution',
    category: 'India GK',
    categoryId: INDIA_CAT_ID,
    subTopic: 'Judicial Landmark Cases',
    difficulty: 'hard',
    examTags: ['UPSC CSE'],
    text: 'In which historic verdict did the Supreme Court propound the "Basic Structure" doctrine of the Constitution?',
    text_en: 'In which historic verdict did the Supreme Court propound the "Basic Structure" doctrine of the Constitution?',
    text_hi: 'सर्वोच्च न्यायालय ने किस ऐतिहासिक फैसले में संविधान के "मूल संरचना" सिद्धांत का प्रतिपादन किया था?',
    options: [
      'Kesavananda Bharati v. State of Kerala (1973)',
      'Golaknath v. State of Punjab (1967)',
      'Minerva Mills v. Union of India (1980)',
      'Maneka Gandhi v. Union of India (1978)'
    ],
    options_en: [
      'Kesavananda Bharati v. State of Kerala (1973)',
      'Golaknath v. State of Punjab (1967)',
      'Minerva Mills v. Union of India (1980)',
      'Maneka Gandhi v. Union of India (1978)'
    ],
    options_hi: [
      'केशवानंद भारती बनाम केरल राज्य (1973)',
      'गोलकनाथ बनाम पंजाब राज्य (1967)',
      'मिनर्वा मिल्स बनाम भारत संघ (1980)',
      'मेनका गांधी बनाम भारत संघ (1978)'
    ],
    correctIndex: 0,
    explanation_en: 'A 13-judge bench in Kesavananda Bharati ruled that Parliament cannot alter the basic structure of the Constitution under Article 368.',
    explanation_hi: 'केशवानंद भारती मामले में 13 जजों की पीठ ने फैसला दिया कि संसद अनुच्छेद 368 के तहत संविधान के मूल ढांचे को नहीं बदल सकती।'
  },
  {
    topicId: 'indian-polity-constitution',
    topicName: 'Indian Polity & Constitution',
    category: 'India GK',
    categoryId: INDIA_CAT_ID,
    subTopic: 'Sources of the Constitution',
    difficulty: 'hard',
    examTags: ['UPSC', 'State PSC'],
    text: 'The concept of "Directive Principles of State Policy" (DPSP) in Part IV was borrowed from which country?',
    text_en: 'The concept of "Directive Principles of State Policy" (DPSP) in Part IV was borrowed from which country?',
    text_hi: 'भाग IV में वर्णित "राज्य के नीति निर्देशक तत्व" (DPSP) की अवधारणा किस देश से ली गई थी?',
    options: ['Ireland', 'United States', 'Australia', 'Canada'],
    options_en: ['Ireland', 'United States', 'Australia', 'Canada'],
    options_hi: ['आयरलैंड', 'संयुक्त राज्य अमेरिका', 'ऑस्ट्रेलिया', 'कनाडा'],
    correctIndex: 0,
    explanation_en: 'The framers borrowed the Directive Principles from the Constitution of Ireland (1937).',
    explanation_hi: 'संविधान निर्माताओं ने राज्य के नीति निर्देशक तत्व 1937 के आयरिश संविधान से ग्रहण किए थे।'
  },
  {
    topicId: 'indian-polity-constitution',
    topicName: 'Indian Polity & Constitution',
    category: 'India GK',
    categoryId: INDIA_CAT_ID,
    subTopic: 'Constitutional Amendments',
    difficulty: 'hard',
    examTags: ['UPSC', 'State PSC'],
    text: 'Which Constitutional Amendment Act paved the way for the introduction of Goods and Services Tax (GST)?',
    text_en: 'Which Constitutional Amendment Act paved the way for the introduction of Goods and Services Tax (GST)?',
    text_hi: 'किस संविधान संशोधन अधिनियम ने वस्तु एवं सेवा कर (GST) की शुरुआत का मार्ग प्रशस्त किया?',
    options: ['101st Amendment Act, 2016', '100th Amendment Act, 2015', '102nd Amendment Act, 2018', '103rd Amendment Act, 2019'],
    options_en: ['101st Amendment Act, 2016', '100th Amendment Act, 2015', '102nd Amendment Act, 2018', '103rd Amendment Act, 2019'],
    options_hi: ['101वां संशोधन अधिनियम, 2016', '100वां संशोधन अधिनियम, 2015', '102वां संशोधन अधिनियम, 2018', '103वां संशोधन अधिनियम, 2019'],
    correctIndex: 0,
    explanation_en: 'The 101st Constitutional Amendment Act introduced GST in India with effect from July 1, 2017.',
    explanation_hi: '101वें संविधान संशोधन अधिनियम (2016) ने 1 जुलाई 2017 से भारत में जीएसटी की शुरुआत की।'
  },
  {
    topicId: 'indian-polity-constitution',
    topicName: 'Indian Polity & Constitution',
    category: 'India GK',
    categoryId: INDIA_CAT_ID,
    subTopic: 'Supreme Court of India',
    difficulty: 'expert',
    examTags: ['UPSC CSE'],
    text: 'Under which Article of the Constitution can the President consult the Supreme Court on questions of law or fact (Advisory Jurisdiction)?',
    text_en: 'Under which Article of the Constitution can the President consult the Supreme Court on questions of law or fact (Advisory Jurisdiction)?',
    text_hi: 'संविधान के किस अनुच्छेद के तहत राष्ट्रपति विधि या तथ्य के प्रश्न पर सर्वोच्च न्यायालय से परामर्श ले सकते हैं (परामर्शदात्री क्षेत्राधिकार)?',
    options: ['Article 143', 'Article 131', 'Article 136', 'Article 141'],
    options_en: ['Article 143', 'Article 131', 'Article 136', 'Article 141'],
    options_hi: ['अनुच्छेद 143', 'अनुच्छेद 131', 'अनुच्छेद 136', 'अनुच्छेद 141'],
    correctIndex: 0,
    explanation_en: 'Article 143 confers advisory jurisdiction upon the Supreme Court of India.',
    explanation_hi: 'अनुच्छेद 143 सर्वोच्च न्यायालय को परामर्श संबंधी क्षेत्राधिकार प्रदान करता है।'
  },
  {
    topicId: 'indian-polity-constitution',
    topicName: 'Indian Polity & Constitution',
    category: 'India GK',
    categoryId: INDIA_CAT_ID,
    subTopic: 'Centre-State Relations',
    difficulty: 'expert',
    examTags: ['UPSC CSE'],
    text: 'Which landmark commission first recommended the establishment of a permanent Inter-State Council under Article 263?',
    text_en: 'Which landmark commission first recommended the establishment of a permanent Inter-State Council under Article 263?',
    text_hi: 'अनुच्छेद 263 के तहत एक स्थायी अंतर-राज्य परिषद की स्थापना की पहली सिफारिश किस प्रमुख आयोग ने की थी?',
    options: ['Sarkaria Commission', 'Punchhi Commission', 'First ARC (1966)', 'Venkatachaliah Commission'],
    options_en: ['Sarkaria Commission', 'Punchhi Commission', 'First ARC (1966)', 'Venkatachaliah Commission'],
    options_hi: ['सरकारिया आयोग', 'पुंछी आयोग', 'प्रथम प्रशासनिक सुधार आयोग', 'वेंकटचलैया आयोग'],
    correctIndex: 0,
    explanation_en: 'The Sarkaria Commission (1988) recommended setting up a permanent Inter-State Council, formed in 1990.',
    explanation_hi: 'सरकारिया आयोग (1988) ने एक स्थायी अंतर-राज्य परिषद की स्थापना की सिफारिश की, जिसे 1990 में गठित किया गया।'
  },
  {
    topicId: 'indian-polity-constitution',
    topicName: 'Indian Polity & Constitution',
    category: 'India GK',
    categoryId: INDIA_CAT_ID,
    subTopic: 'Constitutional Interpretation',
    difficulty: 'expert',
    examTags: ['UPSC CSE'],
    text: 'The constitutional doctrine of "Pith and Substance" is primarily invoked to resolve disputes concerning:',
    text_en: 'The constitutional doctrine of "Pith and Substance" is primarily invoked to resolve disputes concerning:',
    text_hi: 'संवैधानिक "सार और तत्व" (Pith and Substance) का सिद्धांत मुख्य रूप से किसके विवादों को हल करने के लिए लागू किया जाता है?',
    options: [
      'Legislative competence between Union and State legislatures',
      'Territorial nexus in tax imposition',
      'Fundamental rights vs Directive Principles of State Policy',
      'Executive ordinance making powers'
    ],
    options_en: [
      'Legislative competence between Union and State legislatures',
      'Territorial nexus in tax imposition',
      'Fundamental rights vs Directive Principles of State Policy',
      'Executive ordinance making powers'
    ],
    options_hi: [
      'संघ और राज्य विधानसभाओं के बीच विधायी क्षेत्राधिकार व क्षमता',
      'कर लगाने में क्षेत्रीय संबंध (Territorial nexus)',
      'मौलिक अधिकार बनाम राज्य नीति के निर्देशक सिद्धांत',
      'कार्यपालिका की अध्यादेश निर्माण शक्तियां'
    ],
    correctIndex: 0,
    explanation_en: 'The doctrine of Pith and Substance examines the true nature and essence of a law to decide which legislative list it falls under.',
    explanation_hi: 'सार और तत्व का सिद्धांत किसी कानून की वास्तविक प्रकृति की जांच कर यह निर्धारित करता है कि वह किस विधायी सूची के अंतर्गत आता है।'
  },

  // ── WORLD HISTORY & CIVILIZATIONS (World GK) ──
  {
    topicId: 'world-history-civilizations',
    topicName: 'World History & Civilizations',
    category: 'World GK',
    categoryId: WORLD_CAT_ID,
    subTopic: 'French Revolution',
    difficulty: 'easy',
    examTags: ['UPSC', 'SSC CGL'],
    text: 'In which year did the historic storming of the Bastille mark the start of the French Revolution?',
    text_en: 'In which year did the historic storming of the Bastille mark the start of the French Revolution?',
    text_hi: 'बास्तील के ऐतिहासिक पतन ने किस वर्ष फ्रांसीसी क्रांति की शुरुआत की थी?',
    options: ['1789', '1776', '1804', '1815'],
    options_en: ['1789', '1776', '1804', '1815'],
    options_hi: ['1789', '1776', '1804', '1815'],
    correctIndex: 0,
    explanation_en: 'The storming of the Bastille occurred on 14 July 1789, igniting the French Revolution.',
    explanation_hi: '14 जुलाई 1789 को बास्तील के किले पर हमले ने फ्रांसीसी क्रांति की शुरुआत की थी।'
  },
  {
    topicId: 'world-history-civilizations',
    topicName: 'World History & Civilizations',
    category: 'World GK',
    categoryId: WORLD_CAT_ID,
    subTopic: 'Renaissance',
    difficulty: 'easy',
    examTags: ['SSC CGL', 'Railway RRB'],
    text: 'Who painted the iconic masterpiece "Mona Lisa"?',
    text_en: 'Who painted the iconic masterpiece "Mona Lisa"?',
    text_hi: 'प्रसिद्ध उत्कृष्ट कृति "मोना लिसा" को किसने चित्रित किया था?',
    options: ['Leonardo da Vinci', 'Michelangelo', 'Raphael', 'Vincent van Gogh'],
    options_en: ['Leonardo da Vinci', 'Michelangelo', 'Raphael', 'Vincent van Gogh'],
    options_hi: ['लियोनार्डो दा विंची', 'माइकलएंजेलो', 'राफेल', 'विंसेंट वैन गॉग'],
    correctIndex: 0,
    explanation_en: 'Leonardo da Vinci created the Mona Lisa in the early 16th century in Italy.',
    explanation_hi: 'लियोनार्डो दा विंची ने 16वीं शताब्दी की शुरुआत में इटली में मोना लिसा का चित्र बनाया था।'
  },
  {
    topicId: 'world-history-civilizations',
    topicName: 'World History & Civilizations',
    category: 'World GK',
    categoryId: WORLD_CAT_ID,
    subTopic: 'World War I',
    difficulty: 'easy',
    examTags: ['UPSC', 'State PSC'],
    text: 'The assassination of Archduke Franz Ferdinand in 1914 triggered which global conflict?',
    text_en: 'The assassination of Archduke Franz Ferdinand in 1914 triggered which global conflict?',
    text_hi: '1914 में आर्कड्यूक फ्रांज फर्डिनेंड की हत्या ने किस वैश्विक संघर्ष को जन्म दिया था?',
    options: ['World War I', 'World War II', 'Crimean War', 'Franco-Prussian War'],
    options_en: ['World War I', 'World War II', 'Crimean War', 'Franco-Prussian War'],
    options_hi: ['प्रथम विश्व युद्ध', 'द्वितीय विश्व युद्ध', 'क्रीमिया युद्ध', 'फ्रेंको-प्रशिया युद्ध'],
    correctIndex: 0,
    explanation_en: 'The assassination in Sarajevo triggered the alliance chain that led to World War I.',
    explanation_hi: 'साराजेवो में हुई इस हत्या ने संधियों की श्रृंखला को सक्रिय कर प्रथम विश्व युद्ध शुरू किया।'
  },
  {
    topicId: 'world-history-civilizations',
    topicName: 'World History & Civilizations',
    category: 'World GK',
    categoryId: WORLD_CAT_ID,
    subTopic: 'Ancient Egypt',
    difficulty: 'easy',
    examTags: ['SSC CGL', 'Railway RRB'],
    text: 'The Great Pyramid of Giza was constructed as a tomb for which Pharaoh?',
    text_en: 'The Great Pyramid of Giza was constructed as a tomb for which Pharaoh?',
    text_hi: 'गीज़ा का महान पिरामिड किस फिरौन (Pharaoh) के मकबरे के रूप में बनाया गया था?',
    options: ['Khufu (Cheops)', 'Tutankhamun', 'Ramses II', 'Cleopatra'],
    options_en: ['Khufu (Cheops)', 'Tutankhamun', 'Ramses II', 'Cleopatra'],
    options_hi: ['खुफू (चेओप्स)', 'तुतनखामुन', 'रामसेस द्वितीय', 'क्लियोपेट्रा'],
    correctIndex: 0,
    explanation_en: 'The Great Pyramid was built for Fourth Dynasty Pharaoh Khufu around 2560 BCE.',
    explanation_hi: 'महान पिरामिड लगभग 2560 ईसा पूर्व चौथे राजवंश के फिरौन खुफू के लिए बनाया गया था।'
  },
  {
    topicId: 'world-history-civilizations',
    topicName: 'World History & Civilizations',
    category: 'World GK',
    categoryId: WORLD_CAT_ID,
    subTopic: 'American History',
    difficulty: 'easy',
    examTags: ['UPSC', 'SSC CGL'],
    text: 'Who was the first President of the United States of America?',
    text_en: 'Who was the first President of the United States of America?',
    text_hi: 'संयुक्त राज्य अमेरिका के पहले राष्ट्रपति कौन थे?',
    options: ['George Washington', 'Thomas Jefferson', 'John Adams', 'Abraham Lincoln'],
    options_en: ['George Washington', 'Thomas Jefferson', 'John Adams', 'Abraham Lincoln'],
    options_hi: ['जॉर्ज वाशिंगटन', 'थॉमस जेफरसन', 'जॉन एडम्स', 'अब्राहम लिंकन'],
    correctIndex: 0,
    explanation_en: 'George Washington served as the first U.S. President from 1789 to 1797.',
    explanation_hi: 'जॉर्ज वाशिंगटन 1789 से 1797 तक संयुक्त राज्य अमेरिका के पहले राष्ट्रपति रहे।'
  },
  {
    topicId: 'world-history-civilizations',
    topicName: 'World History & Civilizations',
    category: 'World GK',
    categoryId: WORLD_CAT_ID,
    subTopic: 'Russian Revolution',
    difficulty: 'easy',
    examTags: ['UPSC', 'State PSC'],
    text: 'Who was the leader of the Bolshevik party during the October Revolution of 1917?',
    text_en: 'Who was the leader of the Bolshevik party during the October Revolution of 1917?',
    text_hi: '1917 की अक्टूबर क्रांति के दौरान बोल्शेविक पार्टी के नेता कौन थे?',
    options: ['Vladimir Lenin', 'Joseph Stalin', 'Leon Trotsky', 'Nikita Khrushchev'],
    options_en: ['Vladimir Lenin', 'Joseph Stalin', 'Leon Trotsky', 'Nikita Khrushchev'],
    options_hi: ['व्लादिमीर लेनिन', 'जोसेफ स्टालिन', 'लियोन ट्रॉट्स्की', 'निकिता ख्रुश्चेव'],
    correctIndex: 0,
    explanation_en: 'Vladimir Lenin led the Bolsheviks to overthrow the Russian Provisional Government.',
    explanation_hi: 'व्लादिमीर लेनिन ने बोल्शेविकों का नेतृत्व कर अंतरिम सरकार का तख्तापलट किया।'
  },
  {
    topicId: 'world-history-civilizations',
    topicName: 'World History & Civilizations',
    category: 'World GK',
    categoryId: WORLD_CAT_ID,
    subTopic: 'Roman Empire',
    difficulty: 'easy',
    examTags: ['SSC CGL', 'Railway RRB'],
    text: 'Who was the first official Emperor of the Roman Empire?',
    text_en: 'Who was the first official Emperor of the Roman Empire?',
    text_hi: 'रोमन साम्राज्य के पहले आधिकारिक सम्राट कौन थे?',
    options: ['Augustus Caesar', 'Julius Caesar', 'Nero', 'Marcus Aurelius'],
    options_en: ['Augustus Caesar', 'Julius Caesar', 'Nero', 'Marcus Aurelius'],
    options_hi: ['ऑगस्टस सीज़र', 'जूलियस सीज़र', 'नीरो', 'मार्कस ऑरेलियस'],
    correctIndex: 0,
    explanation_en: 'Octavian took the title Augustus and became Rome’s first emperor in 27 BCE.',
    explanation_hi: 'ऑक्टेवियन ने ऑगस्टस की उपाधि ली और 27 ईसा पूर्व में रोम के पहले सम्राट बने।'
  },
  {
    topicId: 'world-history-civilizations',
    topicName: 'World History & Civilizations',
    category: 'World GK',
    categoryId: WORLD_CAT_ID,
    subTopic: 'Mesopotamia',
    difficulty: 'medium',
    examTags: ['UPSC', 'State PSC'],
    text: 'The Code of Hammurabi, one of the earliest legal codes, originated in which civilization?',
    text_en: 'The Code of Hammurabi, one of the earliest legal codes, originated in which civilization?',
    text_hi: 'शुरुआती कानून संहिताओं में से एक, हम्मुराबी की संहिता किस सभ्यता से उत्पन्न हुई थी?',
    options: ['Babylonian (Mesopotamia)', 'Ancient Egypt', 'Indus Valley', 'Ancient Greece'],
    options_en: ['Babylonian (Mesopotamia)', 'Ancient Egypt', 'Indus Valley', 'Ancient Greece'],
    options_hi: ['बेबीलोनियन (मेसोपोटामिया)', 'प्राचीन मिस्र', 'सिंधु घाटी', 'प्राचीन यूनान'],
    correctIndex: 0,
    explanation_en: 'King Hammurabi of Babylon enacted the code c. 1750 BCE, inscribed on a diorite stele.',
    explanation_hi: 'बेबीलोन के राजा हम्मुराबी ने लगभग 1750 ईसा पूर्व में यह संहिता लागू की थी।'
  },
  {
    topicId: 'world-history-civilizations',
    topicName: 'World History & Civilizations',
    category: 'World GK',
    categoryId: WORLD_CAT_ID,
    subTopic: 'Industrial Revolution',
    difficulty: 'medium',
    examTags: ['SSC CGL', 'UPSC'],
    text: 'The Industrial Revolution initially originated during the mid-18th century in which country?',
    text_en: 'The Industrial Revolution initially originated during the mid-18th century in which country?',
    text_hi: '18वीं शताब्दी के मध्य में औद्योगिक क्रांति मूल रूप से किस देश में शुरू हुई थी?',
    options: ['Great Britain', 'France', 'Germany', 'United States'],
    options_en: ['Great Britain', 'France', 'Germany', 'United States'],
    options_hi: ['ग्रेट ब्रिटेन', 'फ्रांस', 'जर्मनी', 'संयुक्त राज्य अमेरिका'],
    correctIndex: 0,
    explanation_en: 'Britain led the Industrial Revolution due to coal deposits, capital, and mechanical inventions.',
    explanation_hi: 'ब्रिटेन ने कोयले के प्रचुर भंडार, पूंजी और यांत्रिक आविष्कारों के कारण औद्योगिक क्रांति का नेतृत्व किया।'
  },
  {
    topicId: 'world-history-civilizations',
    topicName: 'World History & Civilizations',
    category: 'World GK',
    categoryId: WORLD_CAT_ID,
    subTopic: 'World War II',
    difficulty: 'medium',
    examTags: ['State PSC', 'SSC CGL'],
    text: 'Operation Overlord on 6 June 1944 (D-Day) involved Allied landings on the beaches of which region?',
    text_en: 'Operation Overlord on 6 June 1944 (D-Day) involved Allied landings on the beaches of which region?',
    text_hi: '6 जून 1944 को ऑपरेशन ओवरलॉर्ड (D-Day) के तहत मित्र देशों की सेनाएं किस क्षेत्र के समुद्र तटों पर उतरी थीं?',
    options: ['Normandy, France', 'Sicily, Italy', 'Dunkirk, France', 'Crimea, USSR'],
    options_en: ['Normandy, France', 'Sicily, Italy', 'Dunkirk, France', 'Crimea, USSR'],
    options_hi: ['नॉर्मंडी, फ्रांस', 'सिसिली, इटली', 'डनकर्क, फ्रांस', 'क्रीमिया, सोवियत संघ'],
    correctIndex: 0,
    explanation_en: 'Allied forces launched the largest amphibious invasion in history on Normandy’s beaches.',
    explanation_hi: 'मित्र देशों की सेनाओं ने फ्रांस के नॉर्मंडी तट पर इतिहास का सबसे बड़ा समुद्री आक्रमण शुरू किया।'
  },
  {
    topicId: 'world-history-civilizations',
    topicName: 'World History & Civilizations',
    category: 'World GK',
    categoryId: WORLD_CAT_ID,
    subTopic: 'Cold War',
    difficulty: 'medium',
    examTags: ['UPSC', 'State PSC'],
    text: 'In which year did the fall of the Berlin Wall symbolize the collapse of the Iron Curtain in Europe?',
    text_en: 'In which year did the fall of the Berlin Wall symbolize the collapse of the Iron Curtain in Europe?',
    text_hi: 'बर्लिन की दीवार किस वर्ष गिराई गई, जिसने यूरोप में लौह आवरण (Iron Curtain) के पतन का प्रतीक बनाया?',
    options: ['1989', '1991', '1985', '1993'],
    options_en: ['1989', '1991', '1985', '1993'],
    options_hi: ['1989', '1991', '1985', '1993'],
    correctIndex: 0,
    explanation_en: 'The Berlin Wall fell on 9 November 1989, leading to German reunification in 1990.',
    explanation_hi: '9 नवंबर 1989 को बर्लिन की दीवार गिराई गई, जिसके परिणामस्वरूप 1990 में जर्मनी का एकीकरण हुआ।'
  },
  {
    topicId: 'world-history-civilizations',
    topicName: 'World History & Civilizations',
    category: 'World GK',
    categoryId: WORLD_CAT_ID,
    subTopic: 'Ancient Greece',
    difficulty: 'medium',
    examTags: ['UPSC', 'State PSC'],
    text: 'The Peloponnesian War (431–404 BCE) was fought primarily between which two ancient Greek city-states?',
    text_en: 'The Peloponnesian War (431–404 BCE) was fought primarily between which two ancient Greek city-states?',
    text_hi: 'पेलोपोनेसियन युद्ध (431-404 ईसा पूर्व) मुख्य रूप से किन दो प्राचीन ग्रीक नगर-राज्यों के बीच लड़ा गया था?',
    options: ['Athens and Sparta', 'Thebes and Corinth', 'Athens and Troy', 'Sparta and Macedonia'],
    options_en: ['Athens and Sparta', 'Thebes and Corinth', 'Athens and Troy', 'Sparta and Macedonia'],
    options_hi: ['एथेंस और स्पार्टा', 'थीब्स और कोरिंथ', 'एथेंस और ट्रॉय', 'स्पार्टा और मैसेडोनिया'],
    correctIndex: 0,
    explanation_en: 'The Peloponnesian War pitted the Delian League led by Athens against the Peloponnesian League led by Sparta.',
    explanation_hi: 'पेलोपोनेसियन युद्ध एथेंस के नेतृत्व वाली डेलियन लीग और स्पार्टा की पेलोपोनेसियन लीग के बीच हुआ था।'
  },
  {
    topicId: 'world-history-civilizations',
    topicName: 'World History & Civilizations',
    category: 'World GK',
    categoryId: WORLD_CAT_ID,
    subTopic: 'Magna Carta',
    difficulty: 'medium',
    examTags: ['UPSC', 'SSC CGL'],
    text: 'In 1215, King John of England was compelled by his rebel barons to sign which landmark charter?',
    text_en: 'In 1215, King John of England was compelled by his rebel barons to sign which landmark charter?',
    text_hi: '1215 में इंग्लैंड के राजा जॉन को उनके विद्रोही सामंतों ने किस ऐतिहासिक चार्टर पर हस्ताक्षर करने के लिए बाध्य किया था?',
    options: ['Magna Carta', 'Bill of Rights', 'Petition of Right', 'Edict of Nantes'],
    options_en: ['Magna Carta', 'Bill of Rights', 'Petition of Right', 'Edict of Nantes'],
    options_hi: ['मैग्ना कार्टा', 'बिल ऑफ राइट्स', 'पिटीशन ऑफ राइट', 'नैनटेस का फरमान'],
    correctIndex: 0,
    explanation_en: 'Magna Carta Libertatum established the foundational principle that everyone, including the monarch, is subject to law.',
    explanation_hi: 'मैग्ना कार्टा ने यह मौलिक सिद्धांत स्थापित किया कि राजा सहित सभी व्यक्ति कानून के अधीन हैं।'
  },
  {
    topicId: 'world-history-civilizations',
    topicName: 'World History & Civilizations',
    category: 'World GK',
    categoryId: WORLD_CAT_ID,
    subTopic: 'Silk Road',
    difficulty: 'medium',
    examTags: ['State PSC', 'SSC CGL'],
    text: 'The ancient Silk Road trade network was first extensively developed during which Chinese dynasty?',
    text_en: 'The ancient Silk Road trade network was first extensively developed during which Chinese dynasty?',
    text_hi: 'प्राचीन सिल्क रोड व्यापार नेटवर्क का व्यापक विकास सबसे पहले किस चीनी राजवंश के दौरान हुआ था?',
    options: ['Han Dynasty', 'Tang Dynasty', 'Ming Dynasty', 'Qin Dynasty'],
    options_en: ['Han Dynasty', 'Tang Dynasty', 'Ming Dynasty', 'Qin Dynasty'],
    options_hi: ['हान राजवंश', 'तांग राजवंश', 'मिंग राजवंश', 'किन राजवंश'],
    correctIndex: 0,
    explanation_en: 'Emperor Wu of Han expanded westward trade routes starting c. 130 BCE through Zhang Qian’s missions.',
    explanation_hi: 'हान राजवंश के सम्राट वू ने झांग कियान के अभियानों के माध्यम से लगभग 130 ईसा पूर्व सिल्क रूट खोला था।'
  },
  {
    topicId: 'world-history-civilizations',
    topicName: 'World History & Civilizations',
    category: 'World GK',
    categoryId: WORLD_CAT_ID,
    subTopic: 'European Treaties',
    difficulty: 'hard',
    examTags: ['UPSC CSE'],
    text: 'Which landmark 1648 peace treaties brought an end to the Thirty Years’ War and created the modern state system?',
    text_en: 'Which landmark 1648 peace treaties brought an end to the Thirty Years’ War and created the modern state system?',
    text_hi: 'किन 1648 की शांति संधियों ने तीस वर्षीय युद्ध को समाप्त किया और आधुनिक संप्रभु राज्य प्रणाली की नींव रखी?',
    options: ['Peace of Westphalia', 'Treaty of Utrecht', 'Treaty of Versailles', 'Congress of Vienna'],
    options_en: ['Peace of Westphalia', 'Treaty of Utrecht', 'Treaty of Versailles', 'Congress of Vienna'],
    options_hi: ['वेस्टफेलिया की शांति संधि', 'उट्रेच की संधि', 'वर्साय की संधि', 'वियना कांग्रेस'],
    correctIndex: 0,
    explanation_en: 'The Peace of Westphalia (1648) established the concept of state sovereignty (Westphalian sovereignty).',
    explanation_hi: 'वेस्टफेलिया की शांति संधि (1648) ने संप्रभु राष्ट्र-राज्य व्यवस्था की अवधारणा को जन्म दिया।'
  },
  {
    topicId: 'world-history-civilizations',
    topicName: 'World History & Civilizations',
    category: 'World GK',
    categoryId: WORLD_CAT_ID,
    subTopic: 'Meiji Restoration',
    difficulty: 'hard',
    examTags: ['UPSC CSE'],
    text: 'The 1868 Meiji Restoration in Japan brought an end to which feudal military government?',
    text_en: 'The 1868 Meiji Restoration in Japan brought an end to which feudal military government?',
    text_hi: 'जापान में 1868 के मीजी पुनर्स्थापन ने किस सामंती सैन्य शासन का अंत किया था?',
    options: ['Tokugawa Shogunate', 'Kamakura Shogunate', 'Ashikaga Shogunate', 'Heian Court'],
    options_en: ['Tokugawa Shogunate', 'Kamakura Shogunate', 'Ashikaga Shogunate', 'Heian Court'],
    options_hi: ['टोकुगावा शोगुनेट', 'कामाकुरा शोगुनेट', 'आशिकागा शोगुनेट', 'हेइआन दरबार'],
    correctIndex: 0,
    explanation_en: 'The Meiji Restoration overthrew the Tokugawa Shogunate and restored imperial rule under Emperor Meiji.',
    explanation_hi: 'मीजी पुनर्स्थापन ने 265 वर्ष पुराने टोकुगावा शोगुनेट को समाप्त कर सम्राट के अधीन आधुनिक शासन शुरू किया।'
  },
  {
    topicId: 'world-history-civilizations',
    topicName: 'World History & Civilizations',
    category: 'World GK',
    categoryId: WORLD_CAT_ID,
    subTopic: 'Napoleonic Wars',
    difficulty: 'hard',
    examTags: ['UPSC CSE'],
    text: 'Napoleon Bonaparte was decisively defeated by the Seventh Coalition in 1815 at which famous battle?',
    text_en: 'Napoleon Bonaparte was decisively defeated by the Seventh Coalition in 1815 at which famous battle?',
    text_hi: '1815 में सातवें गठबंधन द्वारा किस प्रसिद्ध युद्ध में नेपोलियन बोनापार्ट को अंतिम रूप से पराजित किया गया था?',
    options: ['Battle of Waterloo', 'Battle of Austerlitz', 'Battle of Leipzig', 'Battle of Borodino'],
    options_en: ['Battle of Waterloo', 'Battle of Austerlitz', 'Battle of Leipzig', 'Battle of Borodino'],
    options_hi: ['वाटरलू का युद्ध', 'ऑस्टरलिट्ज़ का युद्ध', 'लीपज़िग का युद्ध', 'बोरोडिनो का युद्ध'],
    correctIndex: 0,
    explanation_en: 'The Duke of Wellington and Field Marshal Blücher defeated Napoleon at Waterloo in present-day Belgium.',
    explanation_hi: 'ड्यूक ऑफ वेलिंगटन और फील्ड मार्शल ब्लुचर ने बेल्जियम में वाटरलू के मैदान में नेपोलियन को परास्त किया।'
  },
  {
    topicId: 'world-history-civilizations',
    topicName: 'World History & Civilizations',
    category: 'World GK',
    categoryId: WORLD_CAT_ID,
    subTopic: 'Byzantine Empire',
    difficulty: 'expert',
    examTags: ['UPSC CSE'],
    text: 'In 1453, Constantinople fell to which Ottoman Sultan, marking the definitive end of the Byzantine Empire?',
    text_en: 'In 1453, Constantinople fell to which Ottoman Sultan, marking the definitive end of the Byzantine Empire?',
    text_hi: '1453 में कांस्टेंटिनोपल (कुस्तुंतुनिया) का पतन किस उस्मानिया सुल्तान के हाथों हुआ, जिसने बीजान्टिन साम्राज्य का अंत किया?',
    options: ['Mehmed II (The Conqueror)', 'Suleiman the Magnificent', 'Selim I', 'Bayezid I'],
    options_en: ['Mehmed II (The Conqueror)', 'Suleiman the Magnificent', 'Selim I', 'Bayezid I'],
    options_hi: ['सुल्तान महमूद द्वितीय (फतेह)', 'सुलेमान द मैग्निफिसेंट', 'सलीम प्रथम', 'बायजीद प्रथम'],
    correctIndex: 0,
    explanation_en: 'Sultan Mehmed II conquered Constantinople on 29 May 1453 at the age of 21, establishing Ottoman dominance.',
    explanation_hi: 'सुल्तान महमूद द्वितीय ने 29 मई 1453 को कुस्तुंतुनिया पर विजय प्राप्त की और उसे अपनी राजधानी बनाया।'
  },
  {
    topicId: 'world-history-civilizations',
    topicName: 'World History & Civilizations',
    category: 'World GK',
    categoryId: WORLD_CAT_ID,
    subTopic: 'Treaty of Tordesillas',
    difficulty: 'expert',
    examTags: ['UPSC CSE'],
    text: 'The 1494 Treaty of Tordesillas divided newly discovered lands outside Europe between which two maritime empires?',
    text_en: 'The 1494 Treaty of Tordesillas divided newly discovered lands outside Europe between which two maritime empires?',
    text_hi: '1494 की तोर्देसिला की संधि ने यूरोप के बाहर नई खोजी गई भूमियों को किन दो समुद्री साम्राज्यों के बीच विभाजित किया था?',
    options: ['Spain and Portugal', 'Britain and France', 'Netherlands and Spain', 'Portugal and Britain'],
    options_en: ['Spain and Portugal', 'Britain and France', 'Netherlands and Spain', 'Portugal and Britain'],
    options_hi: ['स्पेन और पुर्तगाल', 'ब्रिटेन और फ्रांस', 'नीदरलैंड और स्पेन', 'पुर्तगाल और ब्रिटेन'],
    correctIndex: 0,
    explanation_en: 'Sanctioned by Pope Alexander VI, the meridian line gave Brazil and Africa to Portugal, and the Americas to Spain.',
    explanation_hi: 'पोप अलेक्जेंडर छठे द्वारा समर्थित इस संधि ने मेरिडियन रेखा खींचकर ब्राजील/अफ्रीका पुर्तगाल को और अमेरिका स्पेन को सौंपा।'
  },
  {
    topicId: 'world-history-civilizations',
    topicName: 'World History & Civilizations',
    category: 'World GK',
    categoryId: WORLD_CAT_ID,
    subTopic: 'Enlightenment Thinkers',
    difficulty: 'expert',
    examTags: ['UPSC CSE'],
    text: 'Which Enlightenment philosopher formulated the seminal doctrine of "Separation of Powers" in his 1748 work "The Spirit of the Laws"?',
    text_en: 'Which Enlightenment philosopher formulated the seminal doctrine of "Separation of Powers" in his 1748 work "The Spirit of the Laws"?',
    text_hi: 'किस प्रबुद्ध दार्शनिक ने 1748 की अपनी कृति "द स्पिरिट ऑफ द लॉज" में "शक्ति के पृथक्करण" का मौलिक सिद्धांत दिया था?',
    options: ['Baron de Montesquieu', 'Jean-Jacques Rousseau', 'John Locke', 'Voltaire'],
    options_en: ['Baron de Montesquieu', 'Jean-Jacques Rousseau', 'John Locke', 'Voltaire'],
    options_hi: ['बैरोन डी मोंटेस्क्यू', 'जीन-जैक्स रूसो', 'जॉन लॉक', 'वॉल्टेयर'],
    correctIndex: 0,
    explanation_en: 'Montesquieu proposed that political liberty requires dividing power among executive, legislative, and judicial branches.',
    explanation_hi: 'मोंटेस्क्यू ने राजनीतिक स्वतंत्रता की रक्षा के लिए कार्यपालिका, विधायिका और न्यायपालिका के बीच शक्तियों के बंटवारे का प्रतिपादन किया।'
  },

  // ── WORLD CAPITALS & CURRENCIES (World GK) ──
  {
    topicId: 'global-capitals-currencies',
    topicName: 'World Capitals & Currencies',
    category: 'World GK',
    categoryId: WORLD_CAT_ID,
    subTopic: 'European Capitals',
    difficulty: 'easy',
    examTags: ['SSC CGL', 'Railway RRB'],
    text: 'What is the capital city of France?',
    text_en: 'What is the capital city of France?',
    text_hi: 'फ्रांस की राजधानी क्या है?',
    options: ['Paris', 'Lyon', 'Marseille', 'Nice'],
    options_en: ['Paris', 'Lyon', 'Marseille', 'Nice'],
    options_hi: ['पेरिस', 'ल्यों', 'मार्सिले', 'नीस'],
    correctIndex: 0,
    explanation_en: 'Paris is the capital and largest city of France, situated along the Seine River.',
    explanation_hi: 'पेरिस सीन नदी के तट पर स्थित फ्रांस की राजधानी और सबसे बड़ा शहर है।'
  },
  {
    topicId: 'global-capitals-currencies',
    topicName: 'World Capitals & Currencies',
    category: 'World GK',
    categoryId: WORLD_CAT_ID,
    subTopic: 'Asian Currencies',
    difficulty: 'easy',
    examTags: ['SSC CGL', 'Railway RRB'],
    text: 'What is the official currency of Japan?',
    text_en: 'What is the official currency of Japan?',
    text_hi: 'जापान की आधिकारिक मुद्रा क्या है?',
    options: ['Yen (JPY)', 'Won (KRW)', 'Yuan (CNY)', 'Baht (THB)'],
    options_en: ['Yen (JPY)', 'Won (KRW)', 'Yuan (CNY)', 'Baht (THB)'],
    options_hi: ['येन (JPY)', 'वोन (KRW)', 'युआन (CNY)', 'बाथ (THB)'],
    correctIndex: 0,
    explanation_en: 'The Yen (¥) is the official currency of Japan, issued by the Bank of Japan.',
    explanation_hi: 'येन (¥) जापान की आधिकारिक मुद्रा है जिसे बैंक ऑफ जापान जारी करता है।'
  },
  {
    topicId: 'global-capitals-currencies',
    topicName: 'World Capitals & Currencies',
    category: 'World GK',
    categoryId: WORLD_CAT_ID,
    subTopic: 'Oceania Capitals',
    difficulty: 'easy',
    examTags: ['SSC CGL', 'State PSC'],
    text: 'What is the federal capital city of Australia?',
    text_en: 'What is the federal capital city of Australia?',
    text_hi: 'ऑस्ट्रेलिया की संघीय राजधानी क्या है?',
    options: ['Canberra', 'Sydney', 'Melbourne', 'Brisbane'],
    options_en: ['Canberra', 'Sydney', 'Melbourne', 'Brisbane'],
    options_hi: ['कैनबरा', 'सिडनी', 'मेलबर्न', 'ब्रिस्बेन'],
    correctIndex: 0,
    explanation_en: 'Canberra was selected as the compromise capital of Australia in 1908.',
    explanation_hi: 'कैनबरा को 1908 में सिडनी और मेलबर्न के बीच समझौते के रूप में राजधानी चुना गया था।'
  },
  {
    topicId: 'global-capitals-currencies',
    topicName: 'World Capitals & Currencies',
    category: 'World GK',
    categoryId: WORLD_CAT_ID,
    subTopic: 'North American Capitals',
    difficulty: 'easy',
    examTags: ['SSC CGL', 'Railway RRB'],
    text: 'What is the capital city of Canada?',
    text_en: 'What is the capital city of Canada?',
    text_hi: 'कनाडा की राजधानी क्या है?',
    options: ['Ottawa', 'Toronto', 'Vancouver', 'Montreal'],
    options_en: ['Ottawa', 'Toronto', 'Vancouver', 'Montreal'],
    options_hi: ['ओटावा', 'टोरंटो', 'वैंकूवर', 'मॉन्ट्रियल'],
    correctIndex: 0,
    explanation_en: 'Ottawa, located in Ontario along the border with Quebec, is the capital of Canada.',
    explanation_hi: 'ओंटारियो में स्थित ओटावा कनाडा की राजधानी है।'
  },
  {
    topicId: 'global-capitals-currencies',
    topicName: 'World Capitals & Currencies',
    category: 'World GK',
    categoryId: WORLD_CAT_ID,
    subTopic: 'European Currencies',
    difficulty: 'easy',
    examTags: ['SSC CGL', 'Railway RRB'],
    text: 'What is the official currency of the United Kingdom?',
    text_en: 'What is the official currency of the United Kingdom?',
    text_hi: 'यूनाइटेड किंगडम (ब्रिटेन) की आधिकारिक मुद्रा क्या है?',
    options: ['Pound Sterling (GBP)', 'Euro (EUR)', 'Swiss Franc (CHF)', 'Krone (NOK)'],
    options_en: ['Pound Sterling (GBP)', 'Euro (EUR)', 'Swiss Franc (CHF)', 'Krone (NOK)'],
    options_hi: ['पाउंड स्टर्लिंग (GBP)', 'यूरो (EUR)', 'स्विस फ्रैंक (CHF)', 'क्रोन (NOK)'],
    correctIndex: 0,
    explanation_en: 'The British Pound Sterling (£) is the official currency of the UK.',
    explanation_hi: 'ब्रिटिश पाउंड स्टर्लिंग (£) यूके की आधिकारिक मुद्रा है।'
  },
  {
    topicId: 'global-capitals-currencies',
    topicName: 'World Capitals & Currencies',
    category: 'World GK',
    categoryId: WORLD_CAT_ID,
    subTopic: 'South American Capitals',
    difficulty: 'easy',
    examTags: ['UPSC', 'State PSC'],
    text: 'What is the federal capital city of Brazil?',
    text_en: 'What is the federal capital city of Brazil?',
    text_hi: 'ब्राजील की संघीय राजधानी क्या है?',
    options: ['Brasília', 'Rio de Janeiro', 'São Paulo', 'Salvador'],
    options_en: ['Brasília', 'Rio de Janeiro', 'São Paulo', 'Salvador'],
    options_hi: ['ब्रासीलिया', 'रियो डी जेनेरो', 'साओ पाउलो', 'साल्वाडोर'],
    correctIndex: 0,
    explanation_en: 'Brasília, planned by Oscar Niemeyer and Lúcio Costa, became Brazil’s capital in 1960.',
    explanation_hi: 'ब्रासीलिया 1960 में रियो डी जेनेरो के स्थान पर ब्राजील की राजधानी बनी।'
  },
  {
    topicId: 'global-capitals-currencies',
    topicName: 'World Capitals & Currencies',
    category: 'World GK',
    categoryId: WORLD_CAT_ID,
    subTopic: 'Asian Capitals',
    difficulty: 'easy',
    examTags: ['SSC CGL', 'Railway RRB'],
    text: 'What is the capital city of Thailand?',
    text_en: 'What is the capital city of Thailand?',
    text_hi: 'थाईलैंड की राजधानी क्या है?',
    options: ['Bangkok', 'Chiang Mai', 'Phuket', 'Pattaya'],
    options_en: ['Bangkok', 'Chiang Mai', 'Phuket', 'Pattaya'],
    options_hi: ['बैंकॉक', 'चियांग माई', 'फुकेत', 'पटाया'],
    correctIndex: 0,
    explanation_en: 'Bangkok (Krung Thep Maha Nakhon) is the capital and chief port of Thailand.',
    explanation_hi: 'बैंकॉक थाईलैंड की राजधानी और सबसे प्रमुख बंदरगाह शहर है।'
  },
  {
    topicId: 'global-capitals-currencies',
    topicName: 'World Capitals & Currencies',
    category: 'World GK',
    categoryId: WORLD_CAT_ID,
    subTopic: 'Middle East Currencies',
    difficulty: 'medium',
    examTags: ['UPSC', 'SSC CGL'],
    text: 'What is the currency of the United Arab Emirates (UAE)?',
    text_en: 'What is the currency of the United Arab Emirates (UAE)?',
    text_hi: 'संयुक्त अरब अमीरात (UAE) की मुद्रा क्या है?',
    options: ['UAE Dirham (AED)', 'Saudi Riyal (SAR)', 'Kuwaiti Dinar (KWD)', 'Omani Rial (OMR)'],
    options_en: ['UAE Dirham (AED)', 'Saudi Riyal (SAR)', 'Kuwaiti Dinar (KWD)', 'Omani Rial (OMR)'],
    options_hi: ['यूएई दिरहम (AED)', 'सऊदी रियाल (SAR)', 'कुवैती दीनार (KWD)', 'ओमानी रियाल (OMR)'],
    correctIndex: 0,
    explanation_en: 'The UAE Dirham is the legal tender of the United Arab Emirates.',
    explanation_hi: 'यूएई दिरहम संयुक्त अरब अमीरात की वैध मुद्रा है।'
  },
  {
    topicId: 'global-capitals-currencies',
    topicName: 'World Capitals & Currencies',
    category: 'World GK',
    categoryId: WORLD_CAT_ID,
    subTopic: 'African Capitals',
    difficulty: 'medium',
    examTags: ['UPSC', 'State PSC'],
    text: 'What is the political capital city of Nigeria, which replaced Lagos in 1991?',
    text_en: 'What is the political capital city of Nigeria, which replaced Lagos in 1991?',
    text_hi: 'नाइजीरिया की राजनीतिक राजधानी क्या है, जिसने 1991 में लागोस का स्थान लिया था?',
    options: ['Abuja', 'Kano', 'Ibadan', 'Port Harcourt'],
    options_en: ['Abuja', 'Kano', 'Ibadan', 'Port Harcourt'],
    options_hi: ['अबुजा', 'कानो', 'इबादान', 'पोर्ट हारकोर्ट'],
    correctIndex: 0,
    explanation_en: 'Abuja officially replaced coastal Lagos as Nigeria’s planned capital city on 12 December 1991.',
    explanation_hi: '12 दिसंबर 1991 को अबुजा ने आधिकारिक रूप से लागोस की जगह नाइजीरिया की राजधानी का स्थान लिया।'
  },
  {
    topicId: 'global-capitals-currencies',
    topicName: 'World Capitals & Currencies',
    category: 'World GK',
    categoryId: WORLD_CAT_ID,
    subTopic: 'Asian Capitals',
    difficulty: 'medium',
    examTags: ['SSC CGL', 'Railway RRB'],
    text: 'What is the capital city of South Korea?',
    text_en: 'What is the capital city of South Korea?',
    text_hi: 'दक्षिण कोरिया की राजधानी क्या है?',
    options: ['Seoul', 'Busan', 'Incheon', 'Daegu'],
    options_en: ['Seoul', 'Busan', 'Incheon', 'Daegu'],
    options_hi: ['सियोल', 'बुसान', 'इंचियोन', 'डेगू'],
    correctIndex: 0,
    explanation_en: 'Seoul, situated on the Han River, has served as the capital of Korea for over 600 years.',
    explanation_hi: 'हान नदी के तट पर स्थित सियोल 600 से अधिक वर्षों से कोरिया की राजधानी रहा है।'
  },
  {
    topicId: 'global-capitals-currencies',
    topicName: 'World Capitals & Currencies',
    category: 'World GK',
    categoryId: WORLD_CAT_ID,
    subTopic: 'European Capitals',
    difficulty: 'medium',
    examTags: ['UPSC', 'State PSC'],
    text: 'What is the administrative capital of Switzerland?',
    text_en: 'What is the administrative capital of Switzerland?',
    text_hi: 'स्विट्जरलैंड की प्रशासनिक (संघीय) राजधानी कौन सी है?',
    options: ['Bern', 'Zurich', 'Geneva', 'Basel'],
    options_en: ['Bern', 'Zurich', 'Geneva', 'Basel'],
    options_hi: ['बर्न', 'ज्यूरिख', 'जिनेवा', 'बासेल'],
    correctIndex: 0,
    explanation_en: 'Bern is the de facto capital (federal city) and seat of the Swiss government.',
    explanation_hi: 'बर्न स्विट्जरलैंड का संघीय शहर (डी फैक्टो राजधानी) और सरकार का मुख्यालय है।'
  },
  {
    topicId: 'global-capitals-currencies',
    topicName: 'World Capitals & Currencies',
    category: 'World GK',
    categoryId: WORLD_CAT_ID,
    subTopic: 'African Currencies',
    difficulty: 'medium',
    examTags: ['SSC CGL', 'State PSC'],
    text: 'What is the official currency of South Africa?',
    text_en: 'What is the official currency of South Africa?',
    text_hi: 'दक्षिण अफ्रीका की आधिकारिक मुद्रा क्या है?',
    options: ['South African Rand (ZAR)', 'Shilling (KES)', 'Naira (NGN)', 'Cedi (GHS)'],
    options_en: ['South African Rand (ZAR)', 'Shilling (KES)', 'Naira (NGN)', 'Cedi (GHS)'],
    options_hi: ['दक्षिण अफ्रीकी रैंड (ZAR)', 'शिलिंग (KES)', 'नायरा (NGN)', 'सेडी (GHS)'],
    correctIndex: 0,
    explanation_en: 'The Rand (ZAR) is the legal tender of South Africa, named after the Witwatersrand ridge.',
    explanation_hi: 'रैंड (ZAR) दक्षिण अफ्रीका की मुद्रा है, जिसका नाम विटवाटरस्रैंड रिज के नाम पर रखा गया है।'
  },
  {
    topicId: 'global-capitals-currencies',
    topicName: 'World Capitals & Currencies',
    category: 'World GK',
    categoryId: WORLD_CAT_ID,
    subTopic: 'Southeast Asian Capitals',
    difficulty: 'medium',
    examTags: ['UPSC', 'SSC CGL'],
    text: 'What is the designated future capital city of Indonesia located in East Kalimantan?',
    text_en: 'What is the designated future capital city of Indonesia located in East Kalimantan?',
    text_hi: 'पूर्वी कालीमंतन में स्थित इंडोनेशिया की नई नियोजित राजधानी का नाम क्या है?',
    options: ['Nusantara', 'Jakarta', 'Surabaya', 'Bandung'],
    options_en: ['Nusantara', 'Jakarta', 'Surabaya', 'Bandung'],
    options_hi: ['नुसंतारा', 'जकार्ता', 'सुरबाया', 'बांडुंग'],
    correctIndex: 0,
    explanation_en: 'Nusantara is Indonesia’s planned new federal capital, replacing sinking Jakarta.',
    explanation_hi: 'नुसंतारा इंडोनेशिया की नई नियोजित राजधानी है, जो जकार्ता का स्थान ले रही है।'
  },
  {
    topicId: 'global-capitals-currencies',
    topicName: 'World Capitals & Currencies',
    category: 'World GK',
    categoryId: WORLD_CAT_ID,
    subTopic: 'South American Currencies',
    difficulty: 'medium',
    examTags: ['SSC CGL', 'State PSC'],
    text: 'What is the national currency of Argentina?',
    text_en: 'What is the national currency of Argentina?',
    text_hi: 'अर्जेंटीना की राष्ट्रीय मुद्रा क्या है?',
    options: ['Argentine Peso (ARS)', 'Real (BRL)', 'Sol (PEN)', 'Bolivar (VES)'],
    options_en: ['Argentine Peso (ARS)', 'Real (BRL)', 'Sol (PEN)', 'Bolivar (VES)'],
    options_hi: ['अर्जेंटीना पेसो (ARS)', 'रियाल (BRL)', 'सोल (PEN)', 'बोलिवर (VES)'],
    correctIndex: 0,
    explanation_en: 'The Peso is the currency of Argentina, subdivided into 100 centavos.',
    explanation_hi: 'पेसो अर्जेंटीना की राष्ट्रीय मुद्रा है, जो 100 सेंटावो में विभाजित है।'
  },
  {
    topicId: 'global-capitals-currencies',
    topicName: 'World Capitals & Currencies',
    category: 'World GK',
    categoryId: WORLD_CAT_ID,
    subTopic: 'Central Asian Capitals',
    difficulty: 'hard',
    examTags: ['UPSC CSE'],
    text: 'What is the capital city of Kazakhstan, formerly known as Nur-Sultan and Akmola?',
    text_en: 'What is the capital city of Kazakhstan, formerly known as Nur-Sultan and Akmola?',
    text_hi: 'कजाकिस्तान की राजधानी क्या है, जिसे पूर्व में नूर-सुल्तान और अकमोला के नाम से जाना जाता था?',
    options: ['Astana', 'Almaty', 'Shymkent', 'Bishkek'],
    options_en: ['Astana', 'Almaty', 'Shymkent', 'Bishkek'],
    options_hi: ['अस्ताना', 'अल्माटी', 'शिमकेंट', 'बिश्केक'],
    correctIndex: 0,
    explanation_en: 'Astana was renamed Nur-Sultan in 2019 and reverted to Astana in September 2022.',
    explanation_hi: '2019 में अस्ताना का नाम बदलकर नूर-सुल्तान किया गया था और सितंबर 2022 में पुनः अस्ताना कर दिया गया।'
  },
  {
    topicId: 'global-capitals-currencies',
    topicName: 'World Capitals & Currencies',
    category: 'World GK',
    categoryId: WORLD_CAT_ID,
    subTopic: 'Middle Eastern Capitals',
    difficulty: 'hard',
    examTags: ['UPSC CSE'],
    text: 'What is the capital city of Oman, situated along the Gulf of Oman?',
    text_en: 'What is the capital city of Oman, situated along the Gulf of Oman?',
    text_hi: 'ओमान की खाड़ी के किनारे स्थित ओमान की राजधानी क्या है?',
    options: ['Muscat', 'Salalah', 'Sohar', 'Manama'],
    options_en: ['Muscat', 'Salalah', 'Sohar', 'Manama'],
    options_hi: ['मस्कट', 'सलालाह', 'सोहर', 'मनामा'],
    correctIndex: 0,
    explanation_en: 'Muscat has been the historic port capital of the Sultanate of Oman.',
    explanation_hi: 'मस्कट ओमान सल्तनत की ऐतिहासिक बंदरगाह राजधानी है।'
  },
  {
    topicId: 'global-capitals-currencies',
    topicName: 'World Capitals & Currencies',
    category: 'World GK',
    categoryId: WORLD_CAT_ID,
    subTopic: 'Global Currencies',
    difficulty: 'hard',
    examTags: ['UPSC', 'State PSC'],
    text: 'Which country’s currency is the "Lek" (ALL)?',
    text_en: 'Which country’s currency is the "Lek" (ALL)?',
    text_hi: '"लेक" (ALL) किस देश की आधिकारिक मुद्रा है?',
    options: ['Albania', 'Armenia', 'Azerbaijan', 'Belarus'],
    options_en: ['Albania', 'Armenia', 'Azerbaijan', 'Belarus'],
    options_hi: ['अल्बानिया', 'आर्मेनिया', 'अजरबैजान', 'बेलारूस'],
    correctIndex: 0,
    explanation_en: 'The Albanian Lek has been the currency of Albania since 1926.',
    explanation_hi: 'अल्बानियाई लेक 1926 से अल्बानिया की आधिकारिक मुद्रा है।'
  },
  {
    topicId: 'global-capitals-currencies',
    topicName: 'World Capitals & Currencies',
    category: 'World GK',
    categoryId: WORLD_CAT_ID,
    subTopic: 'Island Nation Capitals',
    difficulty: 'expert',
    examTags: ['UPSC CSE'],
    text: 'What is the capital city of the Pacific island nation of Kiribati?',
    text_en: 'What is the capital city of the Pacific island nation of Kiribati?',
    text_hi: 'प्रशांत महासागरीय द्वीप राष्ट्र किरिबाती की राजधानी क्या है?',
    options: ['South Tarawa', 'Suva', 'Nukuʻalofa', 'Apia'],
    options_en: ['South Tarawa', 'Suva', 'Nukuʻalofa', 'Apia'],
    options_hi: ['साउथ तारावा', 'सुवा', 'नुकुअलोफा', 'एपिया'],
    correctIndex: 0,
    explanation_en: 'South Tarawa, situated on the Tarawa Atoll, is the capital of the Republic of Kiribati.',
    explanation_hi: 'तारावा एटोल पर स्थित साउथ तारावा किरिबाती गणराज्य की राजधानी है।'
  },
  {
    topicId: 'global-capitals-currencies',
    topicName: 'World Capitals & Currencies',
    category: 'World GK',
    categoryId: WORLD_CAT_ID,
    subTopic: 'Landlocked Nations',
    difficulty: 'expert',
    examTags: ['UPSC CSE'],
    text: 'Only two doubly landlocked countries exist in the world (surrounded solely by other landlocked countries). One is Liechtenstein; which is the other?',
    text_en: 'Only two doubly landlocked countries exist in the world (surrounded solely by other landlocked countries). One is Liechtenstein; which is the other?',
    text_hi: 'दुनिया में केवल दो दोहरे भू-आबद्ध (doubly landlocked) देश हैं। एक लिकटेंस्टीन है; दूसरा कौन सा है?',
    options: ['Uzbekistan', 'Mongolia', 'Bolivia', 'Paraguay'],
    options_en: ['Uzbekistan', 'Mongolia', 'Bolivia', 'Paraguay'],
    options_hi: ['उज्बेकिस्तान', 'मंगोलिया', 'बोलीविया', 'पराग्वे'],
    correctIndex: 0,
    explanation_en: 'Uzbekistan and Liechtenstein are the world’s only two doubly landlocked nations.',
    explanation_hi: 'उज्बेकिस्तान और लिकटेंस्टीन दुनिया के एकमात्र दो दोहरे भू-आबद्ध देश हैं।'
  },
  {
    topicId: 'global-capitals-currencies',
    topicName: 'World Capitals & Currencies',
    category: 'World GK',
    categoryId: WORLD_CAT_ID,
    subTopic: 'Unique Currencies',
    difficulty: 'expert',
    examTags: ['UPSC CSE'],
    text: 'The currency unit "Ngultrum" (BTN), pegged at par with the Indian Rupee, belongs to which Himalayan nation?',
    text_en: 'The currency unit "Ngultrum" (BTN), pegged at par with the Indian Rupee, belongs to which Himalayan nation?',
    text_hi: 'भारतीय रुपये के सममूल्य पर आंकी गई मुद्रा इकाई "न्गुलट्रम" (BTN) किस हिमालयी देश की है?',
    options: ['Bhutan', 'Nepal', 'Tibet', 'Sikkim'],
    options_en: ['Bhutan', 'Nepal', 'Tibet', 'Sikkim'],
    options_hi: ['भूटान', 'नेपाल', 'तिब्बत', 'सिक्किम'],
    correctIndex: 0,
    explanation_en: 'The Ngultrum is the currency of the Kingdom of Bhutan, pegged 1:1 with INR.',
    explanation_hi: 'न्गुलट्रम भूटान राजशाही की आधिकारिक मुद्रा है, जो भारतीय रुपये के साथ 1:1 पर आंकी गई है।'
  }
];

async function seed() {
  const client = new MongoClient(process.env.DATABASE_URL);
  await client.connect();
  const db = client.db();

  console.log(`Preparing to seed ${QUESTIONS.length} GK questions...`);
  const qCol = db.collection('Question');

  const docs = QUESTIONS.map((q) => {
    const hash = calculateQuestionHash({
      text: q.text,
      options: q.options,
      correctIndex: q.correctIndex,
      category: q.category
    });

    return {
      masterCategory: 'GK',
      category: q.category,
      categoryName: q.category,
      categoryId: q.categoryId,
      topicId: q.topicId,
      topicName: q.topicName,
      subTopic: q.subTopic,
      difficulty: q.difficulty,
      questionType: 'MCQ',
      examTags: q.examTags || [],
      exam: q.examTags || [],
      tags: [...(q.examTags || []), q.subTopic, q.topicName],
      text: q.text,
      text_en: q.text_en,
      text_hi: q.text_hi,
      options: q.options,
      options_en: q.options_en,
      options_hi: q.options_hi,
      options_list: q.options.map((opt, idx) => ({
        id: String(idx + 1),
        text: opt,
        text_en: q.options_en[idx] || opt,
        text_hi: q.options_hi[idx] || opt
      })),
      correct: q.options[q.correctIndex],
      correctAnswer: q.options[q.correctIndex],
      correct_index: q.correctIndex,
      correctIndex: q.correctIndex,
      explanation_en: q.explanation_en,
      explanation_hi: q.explanation_hi,
      status: 'published',
      language: 'en',
      hash,
      source: 'GK Bulk Upload Engine',
      audience: ['adults', 'explorer', 'all'],
      createdAt: new Date(),
      updatedAt: new Date()
    };
  });

  // Insert or upsert by hash
  let inserted = 0;
  for (const doc of docs) {
    const res = await qCol.updateOne(
      { hash: doc.hash },
      { $set: doc },
      { upsert: true }
    );
    if (res.upsertedCount > 0 || res.modifiedCount > 0) inserted++;
  }
  console.log(`Upserted ${inserted} questions.`);

  // Update topic counts in gk_topics
  const topicsCol = db.collection('gk_topics');
  for (const tid of ['ancient-india-history', 'indian-polity-constitution', 'world-history-civilizations', 'global-capitals-currencies']) {
    const count = await qCol.countDocuments({ topicId: tid, status: 'published' });
    await topicsCol.updateOne({ id: tid }, { $set: { questionCount: count, active: true } });
    console.log(`Topic ${tid} has ${count} published questions.`);
  }

  // Also generate initial sets for both categories using gkEngine logic!
  const { DEFAULT_GK_RULES } = await import('../src/lib/gkData.js');
  const { generateGkSetsDryRun, saveGeneratedSets } = await import('../src/lib/gkEngine.js');

  for (const category of ['India GK', 'World GK']) {
    const catTopics = await topicsCol.find({ category, active: true }).sort({ order: 1 }).toArray();
    const catQuestions = await qCol.find({ category, status: 'published' }).toArray();
    const existingSets = await db.collection('gk_sets').find({ category }).toArray();

    const dryRun = generateGkSetsDryRun({
      category,
      language: 'en',
      topics: catTopics,
      questions: catQuestions,
      existingSets,
      rules: DEFAULT_GK_RULES,
      regenerateUnlockedOnly: false,
      allowPartialFinalSet: false,
      pinnedTopicIds: [],
      type: 'all'
    });

    console.log(`[${category}] Generated: ${dryRun.topicSets.length} topic sets, ${dryRun.masterSets.length} master sets.`);
    const saveResult = await saveGeneratedSets({
      db,
      category,
      language: 'en',
      topicSets: dryRun.topicSets,
      masterSets: dryRun.masterSets
    });
    console.log(`[${category}] Saved result:`, saveResult);
  }

  await client.close();
  console.log('Seeding & Set generation complete!');
}

seed().catch(console.error);
