import { NextResponse } from "next/server";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import jsPDF from "jspdf";
import "jspdf-autotable";

export const dynamic = "force-dynamic";

export async function GET() {
  const session = await getServerSession(authOptions);
  if (!session?.user?.id || session.user.isAdmin) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  // Check if user is Pro
  const user = await prisma.user.findUnique({
    where: { id: session.user.id },
    select: { isPro: true },
  });

  if (!user?.isPro) {
    return NextResponse.json({ error: "Pro membership required" }, { status: 403 });
  }

  const favourites = await prisma.favourite.findMany({
    where: { userId: session.user.id },
    include: { question: { include: { category: true } } },
    orderBy: { createdAt: "desc" },
    take: 100, // Limit to 100 questions
  });

  if (favourites.length === 0) {
    return NextResponse.json({ error: "No favorites to export" }, { status: 400 });
  }

  // Get company settings
  const settingsRows = await prisma.setting.findMany({
    where: { key: { in: ["companyName", "companyWebsite"] } },
  });
  const settings = {};
  settingsRows.forEach((r) => (settings[r.key] = r.value));

  const companyName = settings.companyName || "QuizWeb";
  const companyWebsite = settings.companyWebsite || "";

  // Create PDF
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  // Add header with branding
  doc.setFillColor(79, 70, 229); // Indigo color
  doc.rect(0, 0, pageWidth, 40, "F");
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont("helvetica", "bold");
  doc.text(companyName, 20, 25);
  
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text("Study Guide - Favorited Questions", 20, 35);

  // Add watermark
  doc.setTextColor(200, 200, 200);
  doc.setFontSize(40);
  doc.setFont("helvetica", "bold");
  doc.text("PRO MEMBER", pageWidth / 2, pageHeight / 2, { align: "center", angle: 45 });

  // Reset text color
  doc.setTextColor(0, 0, 0);

  // Prepare table data
  const tableData = favourites.map((f, index) => {
    const options = JSON.parse(f.question.options || "[]");
    const correctOption = options[f.question.correctAnswer] || "N/A";
    return [
      index + 1,
      f.question.category?.topic || "General",
      f.question.text.substring(0, 100) + (f.question.text.length > 100 ? "..." : ""),
      correctOption,
    ];
  });

  // Add table
  doc.autoTable({
    startY: 50,
    head: [["#", "Category", "Question", "Correct Answer"]],
    body: tableData,
    theme: "striped",
    headStyles: {
      fillColor: [79, 70, 229],
      textColor: [255, 255, 255],
      fontStyle: "bold",
    },
    styles: {
      fontSize: 9,
      cellPadding: 3,
    },
    columnStyles: {
      0: { cellWidth: 10 },
      1: { cellWidth: 30 },
      2: { cellWidth: 100 },
      3: { cellWidth: 40 },
    },
  });

  // Add footer
  const finalY = doc.lastAutoTable.finalY + 20;
  doc.setFontSize(8);
  doc.setTextColor(128, 128, 128);
  doc.text(
    `Generated by ${companyName} • ${new Date().toLocaleDateString()}`,
    pageWidth / 2,
    pageHeight - 15,
    { align: "center" }
  );

  // Generate PDF buffer
  const pdfBuffer = Buffer.from(doc.output("arraybuffer"));

  // Return PDF
  return new NextResponse(pdfBuffer, {
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `attachment; filename="${companyName}-study-guide.pdf"`,
    },
  });
}
